### ISSUE TITLE
Freezing when unpacking an archive

### ISSUE THREAD

**Issue by EndrII** [miurahr/aqtinstall#114]
Ubuntu 18.04 lxd container.

``` bash
root@LinuxBuilder:~# aqt tool linux tools_ifw 3.2.2 qt.tools.ifw.32
2020-03-24 10:05:04,609 - aqt - WARNING - Specified target combination is not valid: linux tools_ifw qt.tools.ifw.32
2020-03-24 10:05:04,811 - aqt - INFO - Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/qt.tools.ifw.32/3.2.2ifw-linux-x64.7z...
2020-03-24 10:05:04,980 - aqt - INFO - Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/qt.tools.ifw.32/3.2.2ifw-linux-x64.7z
2020-03-24 10:05:17,043 - aqt - INFO - Extracting ifw-linux-x64.7z...
2020-03-24 10:05:17,055 - aqt - INFO - Downloads are Completed.
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

```

stack when force closing aqt
```  bash
^CProcess Process-3:
Process Process-1:
Process Process-2:
Process Process-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/aqt/__init__.py", line 38, in main
    return cli.run()
  File "/usr/local/lib/python3.6/dist-packages/aqt/cli.py", line 220, in run
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/aqt/cli.py", line 141, in run_tool
    logging=self.logger, command=sevenzip, target_dir=output_dir).install()
  File "/usr/local/lib/python3.6/dist-packages/aqt/installer.py", line 148, in install
    sleep(0.5)
KeyboardInterrupt

```

**Comment by miurahr** [comment]
Does v0.7.9 or v0.8 help you solving the issue?

**Comment by EndrII** [comment]
Yes all is work correctly. thanks for help.
