### ISSUE TITLE
Running aqt without arguments produces error

### ISSUE THREAD

**Issue by nyanpasu64** [miurahr/aqtinstall#135]
If you run aqt without arguments, you get a confusing error:

```
C:\Users\nyanpasu64\scoop\apps\consolez\current>aqt
Traceback (most recent call last):
  File "c:\users\nyanpasu64\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nyanpasu64\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nyanpasu64\.local\bin\aqt.exe\__main__.py", line 7, in <module>
  File "c:\users\nyanpasu64\.local\pipx\venvs\aqtinstall\lib\site-packages\aqt\__init__.py", line 38, in main
    return cli.run()
  File "c:\users\nyanpasu64\.local\pipx\venvs\aqtinstall\lib\site-packages\aqt\cli.py", line 248, in run
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

I think you should print help, if no subcommand is recognized. Maybe via `Cli.parser`'s `func`, not sure though.

**Comment by miurahr** [comment]
Thanks for report. Confirmed. Does #136 work as expected?
