### ISSUE TITLE
Fails with 'packages are not found'

### ISSUE THREAD

**Issue by jakubgs** [miurahr/aqtinstall#156]
I tried installing this on a Windows Server Core 2019 with Python installed via [Scoop](https://scoop.sh/) but it fails:
```
PS C:\Users\admin> aqt install 5.14.2 windows desktop win64_msvc2019_64
2020-08-28 14:26:50,133 - aqt - INFO - aqtinstall(aqt) v0.9.5 on Python 3.8.5 [CPython MSC v.1924 64 bit (AMD64)]
2020-08-28 14:26:51,124 - aqt - ERROR - Specified packages are not found while parsing XML of package information!
2020-08-28 14:26:51,124 - aqt - DEBUG - <Updates>
...(lots of XML garbage)...
2020-08-28 14:26:51,202 - aqt - ERROR - Configuration file generation error: (2, 'No such file or directory')
Traceback (most recent call last):
  File "c:\programdata\scoop\apps\python\3.8.5\lib\site-packages\aqt\installer.py", line 141, in make_conf_files
    with open(os.path.join(self.base_dir, qt_version, arch_dir, 'bin', 'qt.conf'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\5.14.2\\msvc2019_64\\bin\\qt.conf'
Traceback (most recent call last):
  File "c:\programdata\scoop\apps\python\3.8.5\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\scoop\apps\python\3.8.5\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\scoop\apps\python\current\Scripts\aqt.exe\__main__.py", line 7, in <module>
  File "c:\programdata\scoop\apps\python\3.8.5\lib\site-packages\aqt\__init__.py", line 38, in main
    return cli.run()
  File "c:\programdata\scoop\apps\python\3.8.5\lib\site-packages\aqt\cli.py", line 340, in run
    return args.func(args)
  File "c:\programdata\scoop\apps\python\3.8.5\lib\site-packages\aqt\cli.py", line 158, in run_install
    installer.finalize()
  File "c:\programdata\scoop\apps\python\3.8.5\lib\site-packages\aqt\installer.py", line 174, in finalize
    self.make_conf_files(target.version, target.arch)
  File "c:\programdata\scoop\apps\python\3.8.5\lib\site-packages\aqt\installer.py", line 157, in make_conf_files
    raise e
  File "c:\programdata\scoop\apps\python\3.8.5\lib\site-packages\aqt\installer.py", line 141, in make_conf_files
    with open(os.path.join(self.base_dir, qt_version, arch_dir, 'bin', 'qt.conf'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\5.14.2\\msvc2019_64\\bin\\qt.conf'
```
No idea what I'm doing wrong.

**Comment by miurahr** [comment]
As message said, there is no support of MSVC 2019 in 5.14.2.

> ...(lots of XML garbage)..

You can find there is no record of msvc2019 in Qt download site database.

You should call
 ```
PS C:\Users\admin> aqt install 5.14.2 windows desktop win64_msvc2017_64
```

Or ask Qt foundation to provide msvc2019 binary for you.

**Comment by jakubgs** [comment]
Oh, I see, that works, thanks for the explanation! Although the error message is not clear at all:
```
ERROR - Specified packages are not found while parsing XML of package information!
```
It doesn't say what package.

Is it talking about the version/first argument?
Is it talking about the target/second argument?
Is it talking about the arch/third argument?
Is it talking about the modules/extra arguments?

Your README states that:
```
aqt [-h][--help][-O | --outputdir <directory>][-b | --base <mirror url>][-E | --external <7zip command>] \
    install <qt-version> <host> <target> [<arch>] [-m all | -m [extra module] [extra module]...]
```
According to your answer what was wrong was the `[<arch>]` argument. if that is the case the error message should be:
```
ERROR - Specified architecture not found while parsing XML of package information!
```
Otherwise it's not very helpful.

Also, the square brackets(`[` and `]`) around `<arch>` indicate that it's optional. But it doesn't work without it. Fails the same way.
