### ISSUE TITLE
qt.conf file not found

### ISSUE THREAD

**Issue by pylipp** [miurahr/aqtinstall#168]
I've been experimenting with the `--archives` option. I want to download the qtvirtualkeyboard module only, so I use 

```
> aqt install 5.14.0 linux desktop -m qtvirtualkeyboard --archives qtvirtualkeyboard -O aqt
```

All required files are installed, yet the program shows an error in the end:

```
2020-10-13 14:15:07,317 - aqt - INFO - aqtinstall(aqt) v0.9.7 on Python 3.8.6 [CPython GCC 5.4.0 20160609]
2020-10-13 14:15:07,694 - aqt - INFO - Downloading qtvirtualkeyboard...
2020-10-13 14:15:07,695 - aqt - DEBUG - Download URL: https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5140/qt.qt5.5140.qtvirtualkeyboard.gcc_64/5.14.0-0-201912110658qtvirtualkeyboard-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z
2020-10-13 14:15:08,041 - aqt - INFO - Redirected URL: http://ftp.fau.de/qtproject/online/qtsdkrepository/linux_x64/desktop/qt5_5140/qt.qt5.5140.qtvirtualkeyboard.gcc_64/5.14.0-0-201912110658qtvirtualkeyboard-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z
2020-10-13 14:15:09,870 - aqt - INFO - Finish installation of qtvirtualkeyboard-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 2.17552955600695
2020-10-13 14:15:09,872 - aqt - ERROR - Configuration file generation error: (2, 'No such file or directory')
Traceback (most recent call last):
  File "/home/philipp/.virtualenvs/pr2-py38/lib/python3.8/site-packages/aqt/installer.py", line 141, in make_conf_files
    with open(os.path.join(self.base_dir, qt_version, arch_dir, 'bin', 'qt.conf'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'aqt/5.14.0/gcc_64/bin/qt.conf'
Traceback (most recent call last):
  File "/home/philipp/.virtualenvs/pr2-py38/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/home/philipp/.virtualenvs/pr2-py38/lib/python3.8/site-packages/aqt/__init__.py", line 38, in main
    return cli.run()
  File "/home/philipp/.virtualenvs/pr2-py38/lib/python3.8/site-packages/aqt/cli.py", line 352, in run
    return args.func(args)
  File "/home/philipp/.virtualenvs/pr2-py38/lib/python3.8/site-packages/aqt/cli.py", line 159, in run_install
    installer.finalize()
  File "/home/philipp/.virtualenvs/pr2-py38/lib/python3.8/site-packages/aqt/installer.py", line 174, in finalize
    self.make_conf_files(target.version, target.arch)
  File "/home/philipp/.virtualenvs/pr2-py38/lib/python3.8/site-packages/aqt/installer.py", line 157, in make_conf_files
    raise e
  File "/home/philipp/.virtualenvs/pr2-py38/lib/python3.8/site-packages/aqt/installer.py", line 141, in make_conf_files
    with open(os.path.join(self.base_dir, qt_version, arch_dir, 'bin', 'qt.conf'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'aqt/5.14.0/gcc_64/bin/qt.conf'
```

**Comment by miurahr** [comment]
You have just installed qtvirtualkeyboard module, and not install qt main files. it is intended behavior and when you use --archives option,  you should handle every things for installation.
