### ISSUE TITLE
"7z" utility somehow not recognized on MacOS/Travic CI

### ISSUE THREAD

**Issue by martinrotter** [miurahr/aqtinstall#184]
See the output, 7zip is installed, and "7z" utility is available on command line. Yet aqtinstall complains.

Called like this: `aqt install -E 7z -O "$QTPATH" 5.15.2 mac desktop clang_64 -m qtwebengine
`
Output of aqtinstall:

```
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 5, in <module>
    from aqt.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/aqt/__init__.py", line 25, in <module>
    from aqt.cli import Cli
  File "/usr/local/lib/python2.7/site-packages/aqt/cli.py", line 83
    raise Exception('Specified 7zip command executable does not exist: {!r}'.format(sevenzip)) from e
```

Output of 7z

```
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,2 CPUs x64)
Usage: 7z <command> [<switches>...] <archive_name> [<file_names>...]
       [<@listfiles...>]
<Commands>
  a : Add files to archive
  b : Benchmark
  d : Delete files from archive
  e : Extract files from archive (without using directory names)
  h : Calculate hash values for files
  i : Show information about supported formats
  l : List contents of archive
  rn : Rename files in archive
  t : Test integrity of archive
  u : Update files to archive
  x : eXtract files with full paths
<Switches>
  -- : Stop switches parsing
  -ai[r[-|0]]{@listfile|!wildcard} : Include archives
  -ax[r[-|0]]{@listfile|!wildcard} : eXclude archives
  -ao{a|s|t|u} : set Overwrite mode
  -an : disable archive_name field
  -bb[0-3] : set output log level
  -bd : disable progress indicator
  -bs{o|e|p}{0|1|2} : set output stream for output/error/progress line
  -bt : show execution time statistics
  -i[r[-|0]]{@listfile|!wildcard} : Include filenames
  -m{Parameters} : set compression Method
    -mmt[N] : set number of CPU threads
  -o{Directory} : set Output directory
  -p{Password} : set Password
  -r[-|0] : Recurse subdirectories
  -sa{a|e|s} : set Archive name mode
  -scc{UTF-8|WIN|DOS} : set charset for for console input/output
  -scs{UTF-8|UTF-16LE|UTF-16BE|WIN|DOS|{id}} : set charset for list files
  -scrc[CRC32|CRC64|SHA1|SHA256|*] : set hash function for x, e, h commands
  -sdel : delete files after compression
  -seml[.] : send archive by email
  -sfx[{name}] : Create SFX archive
  -si[{name}] : read data from stdin
  -slp : set Large Pages mode
  -slt : show technical information for l (List) command
  -snh : store hard links as links
  -snl : store symbolic links as links
  -sni : store NT security information
  -sns[-] : store NTFS alternate streams
  -so : write data to stdout
  -spd : disable wildcard matching for file names
  -spe : eliminate duplication of root folder for extract command
  -spf : use fully qualified file paths
  -ssc[-] : set sensitive case mode
  -ssw : compress shared files
  -stl : set archive timestamp from the most recently modified file
  -stm{HexMask} : set CPU thread affinity mask (hexadecimal number)
  -stx{Type} : exclude archive type
  -t{Type} : Set type of archive
  -u[-][p#][q#][r#][x#][y#][z#][!newArchiveName] : Update options
  -v{Size}[b|k|m|g] : Create volumes
  -w[{path}] : assign Work directory. Empty path means a temporary directory
  -x[r[-|0]]{@listfile|!wildcard} : eXclude filenames
  -y : assume Yes on all queries
```

**Comment by miurahr** [comment]
Does 7zip command is in the PATH on your python  environment?

For example, is a following small snippet working?
```
$ python
>>>  import subprocess
>>>  subprocess.run(['7z', '--help'])
```

**Comment by martinrotter** [comment]
Hard to test, but yes AFAIK 7z is in the path.

But anyway I managed to fix it, my TravisCI script was installing also package homebrew/p7zip which was probably source of the problem. I removed the package, also removed "-E" clause from the call and now it's working.

It seems that aqtinstall does not work well with p7zip package from homebrew, but I workarounded so you can probably close.

**Comment by miurahr** [comment]
An exception is happened at a line  `subprocess.run(sevenzip, '--help'])` to test -E argument that is in sevenzip variable.
That is why I asked you a test. You can add a full path of a 7z command.

**Comment by martinrotter** [comment]
Here is travis output, at the end there is first the output of "7z" command entered into CLI, then output of the above "aqt ... install -E..." command:

https://travis-ci.org/github/martinrotter/rssguard/jobs/746037382

**Comment by miurahr** [comment]
You seems to use deprecated python 2.7 which is not supported by aqtinstall.
And python 7zip support requires python 3.7.5

Here is a part of log you mentions in above comment.
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
7848Collecting aqtinstall
7849  Downloading https://files.pythonhosted.org/packages/3e/8a/28832f092ef7e9a8eb14879ac907a6be29c4dab7509846b276eb152714e3/aqtinstall-0.9.5-py2.py3-none-any.whl
7850Requirement already satisfied: wheel in /usr/local/lib/python2.7/site-packages (from aqtinstall) (0.33.6)
```

It seems better to change from `pip install aqtinstall` to `python3.9 -m pip install aqtinstall` and from `aqt install ` to `python3.9 -m aqt install` in your scripts.

**Comment by martinrotter** [comment]
I checked it and you are actually right. At one point I also realised that but then forgot about it. Nevermind, your tool works just fine now

https://travis-ci.org/github/martinrotter/rssguard/jobs/746136783#L3212
