### ISSUE TITLE
ConnectionError "Connection reset by peer"

### ISSUE THREAD

**Issue by samfrances** [miurahr/aqtinstall#194]
I'm getting the following error when running `aqt install -O $QT_INSTALL_DIR 5.12.4 linux desktop`. I'm getting this on multiple python versions (3.7 and 3.9), multiple machines, and from multiple different network locations.

Any help much appreciated.

```
$ aqt install -O $PWD 5.12.4 linux desktop
2021-01-19 11:44:03,071 - aqt - INFO - aqtinstall(aqt) v0.10.1 on Python 3.9.1 [CPython GCC 5.4.0 20160609]
2021-01-19 11:45:13,280 - aqt - ERROR - Download error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sam/temp/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/sam/temp/venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sam/temp/venv/lib/python3.9/site-packages/aqt/archives.py", line 174, in _download_update_xml
    r = requests.get(update_xml_url)
  File "/home/sam/temp/venv/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/sam/temp/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sam/temp/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sam/temp/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/sam/temp/venv/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by pestophagous** [comment]
It's not just affecting `aqt`: https://forum.qt.io/topic/122837/download-qt-io-is-down

**Comment by pestophagous** [comment]
There are several suggestions about using mirrors posted here: https://forum.qt.io/topic/122837/download-qt-io-is-down

One person mentions using the mirror list on the Wayback Machine, and another user directly mentions `http://ftp.fau.de`

**Comment by pestophagous** [comment]
It seems like this would be the line to edit in the `aqt` sources to point to a mirror:

https://github.com/miurahr/aqtinstall/blob/d21a098a96e7/aqt/archives.py#L75

**Comment by alex-spataru** [comment]
I am now using the `http://mirrors.ocf.berkeley.edu/qt/` mirror for my automated builds, it works without any issues for the moment.

**Comment by sionhughes** [comment]
> I am now using the `http://mirrors.ocf.berkeley.edu/qt/` mirror for my automated builds, it works without any issues for the moment.

Thanks for heads up on that mirror, works a treat! `download.qt.io` down was also killing my automated builds.

**Comment by GilesBathgate** [comment]
https://github.com/jurplel/install-qt-action/issues/78
>> @jurplel It would be a good feature to fallback to a mirror on failure anyway
>
> That would be a feature for aqtinstall I think... too much to maintain on this side

Any chance there could be some kind of `--fallback-mirror` option being added to aqtinstall? The idea being It would just try the mirror if the main URL failed.

**Comment by miurahr** [comment]
> Any chance there could be some kind of --fallback-mirror=http://... option being added to aqtinstall? The idea being It would just try the mirror if the main URL failed.

Need to consider what error should fall back to mirror. when got  404 error it should not.

**Comment by GilesBathgate** [comment]
> > Any chance there could be some kind of --fallback-mirror=http://... option being added to aqtinstall? The idea being It would just try the mirror if the main URL failed.
> 
> Need to consider what error should fall back to mirror. when got 404 error it should not.

I'd have thought 
```python
try:
  download(...)
except (urllib3.exceptions.ProtocolError, requests.exceptions.ConnectionError) e:
   log(e)
   download_from_mirror(...)
```

**Comment by miurahr** [comment]
#196 try to implement fallback mechanism, could you try and check?

**Comment by miurahr** [comment]
When call with ` --fallback http://mirrors.ocf.berkeley.edu/qt/`, aqtinstall try to connect `https://download.qt.io/` then goes to fallback site(http://mirrors.ocf.berkeley.edu/qt/).  This is implemented in PR #196.

There has been an option `--base`.
When call with `--base http://mirrors.ocf.berkeley.edu/qt/`,  aqtinstall  connect to mirror site.

**Comment by miurahr** [comment]
I've updated PR to select fallback site from known mirrors randomly.

**Comment by miurahr** [comment]
v0.11.0 released with the fallback mechanism.

**Comment by jurplel** [comment]
Thanks man, you're a legend.
