### ISSUE TITLE
Can't download ifw.

### ISSUE THREAD

**Issue by EndrII** [miurahr/aqtinstall#195]
``` bash
2021-01-19 14:00:11,964 - aqt - INFO - aqtinstall(aqt) v0.10.1 on Python 3.6.9 [CPython GCC 8.4.0]
2021-01-19 14:02:13,807 - aqt - ERROR - Download error: HTTPSConnectionPool(host='download.qt.io', port=443): Max retries exceeded with url: /online/qtsdkrepository/linux_x64/desktop/tools_ifw/Updates.xml (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')",),))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1808, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1540, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='download.qt.io', port=443): Max retries exceeded with url: /online/qtsdkrepository/linux_x64/desktop/tools_ifw/Updates.xml (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')",),))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aqt/archives.py", line 174, in _download_update_xml
    r = requests.get(update_xml_url)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='download.qt.io', port=443): Max retries exceeded with url: /online/qtsdkrepository/linux_x64/desktop/tools_ifw/Updates.xml (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')",),))
PLATFORM=linux
VERSION=4.0

```

#### command
``` bash
aqt tool --outputdir QIF/data linux tools_ifw 4.0 qt.tools.ifw.40
```

**Comment by introkun** [comment]
download.qt.io is down :(

**Comment by introkun** [comment]
Can we use a mirror somehow?

**Comment by pestophagous** [comment]
I've been using issue #194 to track this (since that issue was opened first). Please see my comment there.

**Comment by miurahr** [comment]
You can use '-b' option to specify mirror site. see  https://aqtinstall.readthedocs.io/en/latest/cli.html#cmdoption-aqt-base

**Comment by EndrII** [comment]
This is problem of a cloud service. See this [answer](https://forum.qt.io/topic/122837/download-qt-io-is-down/17) from qt forum.
>> The cloud service provider is having severe hard drive failure.
