### ISSUE TITLE
Install timing out, regarless of "auto" fallbacks

### ISSUE THREAD

**Issue by Saviq** [miurahr/aqtinstall#215]
Hi, we are seeing frequent timeouts again, which should have been handled by the auto-mirror feature?

```pytb
$ python3 -m aqt install 5.12.10 mac desktop -O ~Qt
2021-02-12 01:48:33,267 - aqt - INFO - aqtinstall(aqt) v0.11.1 on Python 3.9.1 [CPython Clang 11.0.0 (clang-1100.0.33.17)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1106: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 385, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.qt.io', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/aqt/__main__.py", line 28, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/aqt/__init__.py", line 38, in main
    return cli.run()
  File "/usr/local/lib/python3.9/site-packages/aqt/installer.py", line 433, in run
    return args.func(args)
  File "/usr/local/lib/python3.9/site-packages/aqt/installer.py", line 196, in run_install
    qt_archives = QtArchives(os_name, target, qt_version, arch, base, subarchives=archives, modules=modules,
  File "/usr/local/lib/python3.9/site-packages/aqt/archives.py", line 144, in __init__
    self._get_archives(qt_ver_num)
  File "/usr/local/lib/python3.9/site-packages/aqt/archives.py", line 160, in _get_archives
    self._download_update_xml(update_xml_url)
  File "/usr/local/lib/python3.9/site-packages/aqt/archives.py", line 165, in _download_update_xml
    r = requests.get(update_xml_url, timeout=self.timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='download.qt.io', port=443): Read timed out. (read timeout=5)
Error: The process 'python3' failed with exit code 1
```

**Comment by dlyr** [comment]
We notice this also, I think (without any clue) it can arrive because of that the website responded (to ping for instance) but become available when download starts

**Comment by miurahr** [comment]
You can use aqtinstall v1.1.0

**Comment by pajlada** [comment]
Noticed this happening when using aqinstall v1.1.0 as well

```
$ python3 -m aqt install 5.12.10 linux desktop -O /home/runner/work/chatterino2/Qt --external 7z
2021-02-12 16:26:23,042 - aqt - INFO - aqtinstall(aqt) v1.1.0 on Python 3.9.1 [CPython GCC 7.5.0]
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1106: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 385, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.qt.io', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/aqt/__main__.py", line 27, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/aqt/__init__.py", line 38, in main
    return cli.run()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/aqt/installer.py", line 473, in run
    return args.func(args)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/aqt/installer.py", line 222, in run_install
    qt_archives = QtArchives(os_name, target, qt_version, arch, base, subarchives=archives, modules=modules,
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/aqt/archives.py", line 159, in __init__
    self._get_archives(qt_ver_num)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/aqt/archives.py", line 181, in _get_archives
    self._download_update_xml(update_xml_url)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/aqt/archives.py", line 186, in _download_update_xml
    r = requests.get(update_xml_url, timeout=self.timeout)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='download.qt.io', port=443): Read timed out. (read timeout=5)
```

**Comment by miurahr** [comment]
Thanks for checking reproduce.
```
except (ConnectionResetError, requests.exceptions.ConnectionError):
```

Now catching errors above, but we got `requests.exceptions.ReadTimeout` so it crashes.

**Comment by miurahr** [comment]
v1.1.1 is out with patch to catch ReadTimeout error.
@Saviq @pajlada @dlyr does it sove your case?

**Comment by pajlada** [comment]
> v1.1.1 is out with patch to catch ReadTimeout error.
> @Saviq @pajlada @dlyr does it sove your case?

Unfortunately unable to reproduce (as the network connectivity is stable now), and I'm unable to force the same network conditions. We will be using v1.1.1 going forward and will be sure to make an issue/re-open this issue if I notice the same instability.
Thank you for the quick fix and release!

**Comment by dlyr** [comment]
For the moment everything works fine on our side, I'll comment if I can see any problems arise.
