### ISSUE TITLE
Sometimes fails with connection error

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#22]
It is not just fials but generating traceback. It should be more graceful when connection failed.

Log:

```
Traceback (most recent call last):
  File "/home/vsts/work/1/s/aqtinst", line 7, in <module>
    sys.exit(main())
  File "/home/vsts/work/1/s/aqt/__init__.py", line 59, in main
    QtInstaller(QtArchives(os_name, qt_version, target, arch)).install()
  File "/home/vsts/work/1/s/aqt/installer.py", line 79, in install
    p.map(self.retrieve_archive, archives)
  File "/opt/hostedtoolcache/Python/2.7.15/x64/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/hostedtoolcache/Python/2.7.15/x64/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
requests.exceptions.ConnectionError: HTTPConnectionPool(host='mirrors.tuna.tsinghua.edu.cn', port=80): Max retries exceeded with url: /qt/online/qtsdkrepository/linux_x64/desktop/qt5_5121/qt.qt5.5121.qtdatavis3d.gcc_64/5.12.1-0-201901300517qtdatavis3d-Linux-RHEL_7_4-GCC-Linux-RHEL_7_4-X86_64.7z (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f7e347dd0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```
[Azure pipelines Ubuntu with Python2.7](https://dev.azure.com/miurahr/github/_build/results?buildId=494&view=logs&jobId=4135a7cf-91fe-57ca-d2c1-7f5272ef67da&taskId=5bd3be22-9c91-5269-d6f4-48695cdc9b69&lineStart=11730&lineEnd=11741&colStart=1&colEnd=466)

**Comment by miurahr** [comment]
Fix commited
