### ISSUE TITLE
Socket timeouts continue to break things

### ISSUE THREAD

**Issue by Saviq** [miurahr/aqtinstall#223]
I've just seen a timeout with 1.1.3 on Windows:

```plain
2021-03-02T17:41:48.9926147Z ##[group]Run jurplel/install-qt-action@v2
2021-03-02T17:41:48.9927020Z with:
2021-03-02T17:41:48.9928043Z   extra: -b http://mirrors.ocf.berkeley.edu/qt/
2021-03-02T17:41:48.9943623Z   version: 5.15.2
2021-03-02T17:41:48.9944536Z   target: desktop
2021-03-02T17:41:48.9946094Z   install-deps: true
2021-03-02T17:41:48.9946777Z   cached: false
2021-03-02T17:41:48.9947415Z   setup-python: true
2021-03-02T17:41:48.9948081Z   set-env: true
2021-03-02T17:41:48.9948707Z   tools-only: false
2021-03-02T17:41:48.9949345Z   aqtversion: ==1.1.3
2021-03-02T17:41:48.9949991Z   py7zrversion: ==0.14.0
2021-03-02T17:41:48.9950608Z env:
2021-03-02T17:41:48.9951200Z   HEAD_REF: ci614923569
2021-03-02T17:41:48.9952148Z   RUN_URL: https://github.com/canonical/multipass-private/actions/runs/614923569
2021-03-02T17:41:48.9953133Z   BUILD_DIR: ../build
2021-03-02T17:41:48.9953759Z ##[endgroup]
2021-03-02T17:41:49.2760708Z Successfully setup CPython (3.9.1)
2021-03-02T17:41:49.2775315Z [command]python -m pip install setuptools wheel
2021-03-02T17:42:04.0284941Z Requirement already satisfied: setuptools in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (49.2.1)
2021-03-02T17:42:04.9314507Z Collecting wheel
2021-03-02T17:42:05.0082460Z   Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
2021-03-02T17:42:05.0679383Z Installing collected packages: wheel
2021-03-02T17:42:05.2320892Z Successfully installed wheel-0.36.2
2021-03-02T17:42:05.4277972Z [command]python -m pip install py7zr==0.14.0
2021-03-02T17:42:05.9939726Z Collecting py7zr==0.14.0
2021-03-02T17:42:06.0683437Z   Downloading py7zr-0.14.0-py3-none-any.whl (68 kB)
2021-03-02T17:42:06.1490544Z Collecting texttable
2021-03-02T17:42:06.1656639Z   Downloading texttable-1.6.3-py2.py3-none-any.whl (10 kB)
2021-03-02T17:42:06.2031188Z Collecting multivolumefile<0.3.0,>=0.2.0
2021-03-02T17:42:06.2186722Z   Downloading multivolumefile-0.2.2-py3-none-any.whl (16 kB)
2021-03-02T17:42:06.3235959Z Collecting pyzstd<0.15.0,>=0.14.1
2021-03-02T17:42:06.3401726Z   Downloading pyzstd-0.14.2-cp39-cp39-win_amd64.whl (197 kB)
2021-03-02T17:42:06.4179893Z Collecting bcj-cffi<0.6.0,>=0.5.0
2021-03-02T17:42:06.4331520Z   Downloading bcj_cffi-0.5.0-cp39-cp39-win_amd64.whl (20 kB)
2021-03-02T17:42:06.4866898Z Collecting ppmd-cffi<0.4.0,>=0.3.1
2021-03-02T17:42:06.5032479Z   Downloading ppmd_cffi-0.3.3-cp39-cp39-win_amd64.whl (44 kB)
2021-03-02T17:42:06.7526975Z Collecting pycryptodome
2021-03-02T17:42:06.7705208Z   Downloading pycryptodome-3.10.1-cp35-abi3-win_amd64.whl (1.6 MB)
2021-03-02T17:42:07.2107882Z Collecting cffi>=1.14.0
2021-03-02T17:42:07.2277376Z   Downloading cffi-1.14.5-cp39-cp39-win_amd64.whl (179 kB)
2021-03-02T17:42:07.2912650Z Collecting pycparser
2021-03-02T17:42:07.3062312Z   Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
2021-03-02T17:42:07.4630643Z Installing collected packages: pycparser, cffi, texttable, pyzstd, pycryptodome, ppmd-cffi, multivolumefile, bcj-cffi, py7zr
2021-03-02T17:42:09.1863702Z Successfully installed bcj-cffi-0.5.0 cffi-1.14.5 multivolumefile-0.2.2 ppmd-cffi-0.3.3 py7zr-0.14.0 pycparser-2.20 pycryptodome-3.10.1 pyzstd-0.14.2 texttable-1.6.3
2021-03-02T17:42:09.3040732Z [command]python -m pip install aqtinstall==1.1.3
2021-03-02T17:42:10.0724443Z Collecting aqtinstall==1.1.3
2021-03-02T17:42:10.0725716Z   Downloading aqtinstall-1.1.3-py2.py3-none-any.whl (26 kB)
2021-03-02T17:42:10.0727279Z Requirement already satisfied: py7zr!=0.10.0,>=0.9.9 in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (from aqtinstall==1.1.3) (0.14.0)
2021-03-02T17:42:10.0729158Z Requirement already satisfied: wheel in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (from aqtinstall==1.1.3) (0.36.2)
2021-03-02T17:42:10.0730320Z Collecting packaging
2021-03-02T17:42:10.0731238Z   Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
2021-03-02T17:42:10.1631197Z Collecting requests
2021-03-02T17:42:10.1782904Z   Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
2021-03-02T17:42:10.2144526Z Requirement already satisfied: texttable in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (from aqtinstall==1.1.3) (1.6.3)
2021-03-02T17:42:10.2578040Z Requirement already satisfied: bcj-cffi<0.6.0,>=0.5.0 in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (from py7zr!=0.10.0,>=0.9.9->aqtinstall==1.1.3) (0.5.0)
2021-03-02T17:42:10.2586988Z Requirement already satisfied: multivolumefile<0.3.0,>=0.2.0 in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (from py7zr!=0.10.0,>=0.9.9->aqtinstall==1.1.3) (0.2.2)
2021-03-02T17:42:10.2592482Z Requirement already satisfied: pycryptodome in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (from py7zr!=0.10.0,>=0.9.9->aqtinstall==1.1.3) (3.10.1)
2021-03-02T17:42:10.2600908Z Requirement already satisfied: ppmd-cffi<0.4.0,>=0.3.1 in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (from py7zr!=0.10.0,>=0.9.9->aqtinstall==1.1.3) (0.3.3)
2021-03-02T17:42:10.2611055Z Requirement already satisfied: pyzstd<0.15.0,>=0.14.1 in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (from py7zr!=0.10.0,>=0.9.9->aqtinstall==1.1.3) (0.14.2)
2021-03-02T17:42:10.2739464Z Requirement already satisfied: cffi>=1.14.0 in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (from bcj-cffi<0.6.0,>=0.5.0->py7zr!=0.10.0,>=0.9.9->aqtinstall==1.1.3) (1.14.5)
2021-03-02T17:42:10.2757679Z Requirement already satisfied: pycparser in c:\hostedtoolcache\windows\python\3.9.1\x64\lib\site-packages (from cffi>=1.14.0->bcj-cffi<0.6.0,>=0.5.0->py7zr!=0.10.0,>=0.9.9->aqtinstall==1.1.3) (2.20)
2021-03-02T17:42:10.3847978Z Collecting pyparsing>=2.0.2
2021-03-02T17:42:10.4000429Z   Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
2021-03-02T17:42:10.4911403Z Collecting chardet<5,>=3.0.2
2021-03-02T17:42:10.5063725Z   Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
2021-03-02T17:42:10.5930348Z Collecting certifi>=2017.4.17
2021-03-02T17:42:10.6090031Z   Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
2021-03-02T17:42:10.6770334Z Collecting idna<3,>=2.5
2021-03-02T17:42:10.6914623Z   Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
2021-03-02T17:42:10.8130375Z Collecting urllib3<1.27,>=1.21.1
2021-03-02T17:42:10.8291377Z   Downloading urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
2021-03-02T17:42:10.9826535Z Installing collected packages: urllib3, pyparsing, idna, chardet, certifi, requests, packaging, aqtinstall
2021-03-02T17:42:12.7480772Z Successfully installed aqtinstall-1.1.3 certifi-2020.12.5 chardet-4.0.0 idna-2.10 packaging-20.9 pyparsing-2.4.7 requests-2.25.1 urllib3-1.26.3
2021-03-02T17:42:12.8174666Z [command]python -m aqt install 5.15.2 windows desktop win64_msvc2019_64 -O D:\a\multipass-private/Qt -b http://mirrors.ocf.berkeley.edu/qt/
2021-03-02T17:42:14.2855892Z 2021-03-02 17:42:14,283 - aqt - INFO - aqtinstall(aqt.installer) vunknown on Python 3.9.1 [CPython MSC v.1927 64 bit (AMD64)]
2021-03-02T17:43:30.0821400Z Download error: HTTPConnectionPool(host='mirrors.ocf.berkeley.edu', port=80): Read timed out.
2021-03-02T17:44:46.4236624Z Download error: HTTPConnectionPool(host='mirrors.ocf.berkeley.edu', port=80): Read timed out.
2021-03-02T17:44:46.4258114Z multiprocessing.pool.RemoteTraceback: 
2021-03-02T17:44:46.4265241Z """
2021-03-02T17:44:46.4267172Z Traceback (most recent call last):
2021-03-02T17:44:46.4269029Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\urllib3\response.py", line 438, in _error_catcher
2021-03-02T17:44:46.4270558Z     yield
2021-03-02T17:44:46.4274463Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\urllib3\response.py", line 519, in read
2021-03-02T17:44:46.4276067Z     data = self._fp.read(amt) if not fp_closed else b""
2021-03-02T17:44:46.4277298Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\http\client.py", line 458, in read
2021-03-02T17:44:46.4278399Z     n = self.readinto(b)
2021-03-02T17:44:46.4280418Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\http\client.py", line 502, in readinto
2021-03-02T17:44:46.4281710Z     n = self.fp.readinto(b)
2021-03-02T17:44:46.4282845Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\socket.py", line 704, in readinto
2021-03-02T17:44:46.4283972Z     return self._sock.recv_into(b)
2021-03-02T17:44:46.4286436Z socket.timeout: timed out
2021-03-02T17:44:46.4287064Z 
2021-03-02T17:44:46.4288025Z During handling of the above exception, another exception occurred:
2021-03-02T17:44:46.4288795Z 
2021-03-02T17:44:46.4289549Z Traceback (most recent call last):
2021-03-02T17:44:46.4291092Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\requests\models.py", line 753, in generate
2021-03-02T17:44:46.4292527Z     for chunk in self.raw.stream(chunk_size, decode_content=True):
2021-03-02T17:44:46.4293963Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\urllib3\response.py", line 576, in stream
2021-03-02T17:44:46.4295819Z     data = self.read(amt=amt, decode_content=decode_content)
2021-03-02T17:44:46.4298770Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\urllib3\response.py", line 541, in read
2021-03-02T17:44:46.4301399Z     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
2021-03-02T17:44:46.4305672Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\contextlib.py", line 135, in __exit__
2021-03-02T17:44:46.4308834Z     self.gen.throw(type, value, traceback)
2021-03-02T17:44:46.4310290Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
2021-03-02T17:44:46.4311798Z     raise ReadTimeoutError(self._pool, None, "Read timed out.")
2021-03-02T17:44:46.4313585Z urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='mirrors.ocf.berkeley.edu', port=80): Read timed out.
2021-03-02T17:44:46.4315040Z 
2021-03-02T17:44:46.4316017Z During handling of the above exception, another exception occurred:
2021-03-02T17:44:46.4316814Z 
2021-03-02T17:44:46.4317594Z Traceback (most recent call last):
2021-03-02T17:44:46.4319892Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\multiprocessing\pool.py", line 125, in worker
2021-03-02T17:44:46.4321080Z     result = (True, func(*args, **kwds))
2021-03-02T17:44:46.4322186Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\multiprocessing\pool.py", line 51, in starmapstar
2021-03-02T17:44:46.4325196Z     return list(itertools.starmap(args[0], args[1]))
2021-03-02T17:44:46.4326479Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\aqt\installer.py", line 516, in installer
2021-03-02T17:44:46.4327543Z     raise e
2021-03-02T17:44:46.4328571Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\aqt\installer.py", line 507, in installer
2021-03-02T17:44:46.4329719Z     for chunk in r.iter_content(chunk_size=8196):
2021-03-02T17:44:46.4330910Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\requests\models.py", line 760, in generate
2021-03-02T17:44:46.4332059Z     raise ConnectionError(e)
2021-03-02T17:44:46.4333534Z requests.exceptions.ConnectionError: HTTPConnectionPool(host='mirrors.ocf.berkeley.edu', port=80): Read timed out.
2021-03-02T17:44:46.4334980Z """
2021-03-02T17:44:46.4335304Z 
2021-03-02T17:44:46.4336100Z The above exception was the direct cause of the following exception:
2021-03-02T17:44:46.4336710Z 
2021-03-02T17:44:46.4337334Z Traceback (most recent call last):
2021-03-02T17:44:46.4338363Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\runpy.py", line 197, in _run_module_as_main
2021-03-02T17:44:46.4340056Z     return _run_code(code, main_globals, None,
2021-03-02T17:44:46.4341063Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\runpy.py", line 87, in _run_code
2021-03-02T17:44:46.4342022Z     exec(code, run_globals)
2021-03-02T17:44:46.4343070Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\aqt\__main__.py", line 27, in <module>
2021-03-02T17:44:46.4344281Z     sys.exit(main())
2021-03-02T17:44:46.4345317Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\aqt\__init__.py", line 38, in main
2021-03-02T17:44:46.4346314Z     return cli.run()
2021-03-02T17:44:46.4347350Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\aqt\installer.py", line 471, in run
2021-03-02T17:44:46.4348394Z     return args.func(args)
2021-03-02T17:44:46.4349495Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\aqt\installer.py", line 234, in run_install
2021-03-02T17:44:46.4350742Z     self.call_installer(qt_archives, output_dir, sevenzip)
2021-03-02T17:44:46.4352039Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\aqt\installer.py", line 169, in call_installer
2021-03-02T17:44:46.4353191Z     pool.starmap(installer, tasks)
2021-03-02T17:44:46.4354394Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\multiprocessing\pool.py", line 372, in starmap
2021-03-02T17:44:46.4355928Z     return self._map_async(func, iterable, starmapstar, chunksize).get()
2021-03-02T17:44:46.4357173Z   File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\multiprocessing\pool.py", line 771, in get
2021-03-02T17:44:46.4358176Z     raise self._value
2021-03-02T17:44:46.4359162Z requests.exceptions.ConnectionError: None: None
2021-03-02T17:44:46.4365355Z ##[error]The process 'python' failed with exit code 1
```

**Comment by Saviq** [comment]
Would this be the case only when `-b <mirror>` is given?

**Comment by miurahr** [comment]
You have already specify the mirror server with `-b` option, aqtinstall gives up when timeout happened.
If not specified, aqtinstall try to connect `download.qt.io` and then redirected to mirror server  by 30x response.
When aqtinstall got timeout from the server `download.qt.io` specified, aqtinstall try to find another mirror.

**Comment by Saviq** [comment]
ACK, I've removed the `-b <mirror>` now, sorry for the noise.

**Comment by miurahr** [comment]
Always feedback is welcome.
I think we should not automatically redirect another mirror when obviously specified, but crash/stack trace is not good.
