### ISSUE TITLE
pip install aqtinstall requires Visual Studio due to pycryptodome needed by py7zr?

### ISSUE THREAD

**Issue by lebarsfa** [miurahr/aqtinstall#230]
Hello,

I would like to provide simple instructions to students so that they can easily get Qt Creator+Qt SDK 5.15.2 for MinGW 8.1.0 64 bit. It is possible to get it to work, but in the process I realize that Visual Studio needs to be installed, which is a bit a pity since I wanted  to use MinGW, and even a minimal Visual Studio installation is still quite big compared to the rest (especially for students hard disks that are often full!). 

Here are the steps that I do:
- Get a clean install of Windows 10 20H2
- Install Chocolatey
- `choco install -y python --version=3.6.8`
- `pip install aqtinstall`

At some point:
```Python
Collecting pycryptodome (from py7zr!=0.10.0,>=0.9.9->aqtinstall)
  Downloading https://files.pythonhosted.org/packages/88/7f/740b99ffb8173ba9d20eb890cc05187677df90219649645aca7e44eb8ff4/pycryptodome-3.10.1.tar.gz (3.8MB)
    100% |████████████████████████████████| 3.8MB 654kB/s
    Complete output from command python setup.py egg_info:
    Testing support for clang
    Traceback (most recent call last):
      File "c:\python36\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\1\AppData\Local\Temp\pip-install-wpi3afz2\pycryptodome\setup.py", line 468, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\1\AppData\Local\Temp\pip-install-wpi3afz2\pycryptodome\compiler_opt.py", line 341, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\1\AppData\Local\Temp\pip-install-wpi3afz2\pycryptodome\compiler_opt.py", line 251, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\1\AppData\Local\Temp\pip-install-wpi3afz2\pycryptodome\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "c:\python36\lib\distutils\_msvccompiler.py", line 345, in compile
        self.initialize()
      File "c:\python36\lib\distutils\_msvccompiler.py", line 238, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\python36\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\python36\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\python36\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\python36\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
```
I realize that this is just due to py7zr, which is not strictly necessary if I remove https://github.com/miurahr/aqtinstall/blob/87976781516cf2b166318be9b09f315450127fcc/aqt/installer.py#L36 and https://github.com/miurahr/aqtinstall/blob/87976781516cf2b166318be9b09f315450127fcc/setup.cfg#L38 and install 7zip. Then (after installing manually my modified version of `git clone https://github.com/miurahr/aqtinstall` using `pip install requests packaging texttable & pip install -e aqtinstall`) I can run `aqt install -E 7z --outputdir C:\Qt 5.15.2 windows desktop win64_mingw81 -m qtcharts qtscript`, I can prepare a `%APPDATA%\QtProject\qtcreator\qtversion.xml` file 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE QtCreatorQtVersions>
<!-- Written by QtCreator 4.14.2, 2021-04-03T23:30:20. -->
<qtcreator>
 <data>
  <variable>QtVersion.0</variable>
  <valuemap type="QVariantMap">
   <value type="QString" key="QMakePath">C:/Qt/5.15.2/mingw81_64/bin/qmake.exe</value>
   <value type="QString" key="QtVersion.Type">Qt4ProjectManager.QtVersion.Desktop</value>
  </valuemap>
 </data>
 <data>
  <variable>Version</variable>
  <value type="int">1</value>
 </data>
</qtcreator>
```
 and then run
 `choco install -y mingw --version=8.1.0 & choco install -y qtcreator`.

Is there a cleaner way to avoid Visual Studio installation?

**Comment by KOLANICH** [comment]
I guess the best you can do is a torrent with 7ziped  Qt Creator + Qt unpacked from their installers. This way no installation is needed, just unpacking the archive somewhere and using.

**Comment by miurahr** [comment]
pycryptdome distributes binary packages but it build deprecated CPython2.7 and CPython3.5 binaries, not current CPython 3.6 and later.
As you know, python 2.7 and 3.5 has already been end of life.
aqtinstall depends several python libraries, some of which is only support python3.6 and later, so you can only source package of pycryptodme.

IMHO, it is pycryptodome issue.

**Comment by miurahr** [comment]
Have you already done `pip install wheel`? Pip always install packages  from source without `wheel` on your system.

**Comment by pzhlkj6612** [comment]
Or try `pip install --only-binary :all: aqtinstall` and see the error message?

**Comment by miurahr** [comment]
I can reproduce the behavior reported.

@lebarsfa  **You should run `pip install -U pip` before `pip install aqtinstall`.**
New version of PIP handles binary packages properly. A default version of pip bundled with Python 3.6.8 is too old.

**Comment by lebarsfa** [comment]
Many thanks for all your answers, all are good workarounds!

However, I must say that I also found a similar problem in the case of a 32 bit environment: https://pypi.org/project/bcj-cffi/ does not have 32 bit binaries...

In fact, Windows is missing something like `sudo apt install qt5-default` Ubuntu package, so I just tried to submit an equivalent Chocolatey package which installs and use `aqt`, see https://community.chocolatey.org/packages/qt5-default/5.15.2 (all other existing Qt SDK packages on Chocolatey seem to be old). I don't know yet if it will get approved (maybe due to the problem in 32 bit, but I noticed `qtcreator` package does not seem to work in 32 bit as well, there might be also licensing problems, etc.), but I think this could help new potential users of Qt SDK.

**Comment by pzhlkj6612** [comment]
> https://pypi.org/project/bcj-cffi/ does not have 32 bit binaries...

+1. I ran into the same problem.

**Comment by miurahr** [comment]
bcj-cffi releases win32 binary. You can try aqtinstall  again now.

**Comment by lebarsfa** [comment]
@miurahr Thank you for publishing the 32 bit binaries, it works!

However, please note that an error happens in the middle, without preventing aqtinstall installation though:

```Python
PS C:\Users\1\Downloads> cmd /c "refreshenv & pip install -U pip & pip install aqtinstall"
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
Requirement already satisfied: pip in c:\python39\lib\site-packages (21.0.1)
Collecting aqtinstall
  Downloading aqtinstall-1.1.4-py2.py3-none-any.whl (26 kB)
Collecting texttable
  Downloading texttable-1.6.3-py2.py3-none-any.whl (10 kB)
Collecting py7zr!=0.10.0,>=0.9.9
  Downloading py7zr-0.15.0-py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 4.5 MB/s
Collecting wheel
  Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting packaging
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB ...
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 3.8 MB/s
Collecting bcj-cffi<0.6.0,>=0.5.0
  Downloading bcj_cffi-0.5.1-cp39-cp39-win32.whl (20 kB)
Collecting pycryptodome
  Downloading pycryptodome-3.10.1-cp35-abi3-win32.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 6.8 MB/s
Collecting pyzstd<0.15.0,>=0.14.4
  Downloading pyzstd-0.14.4-cp39-cp39-win32.whl (184 kB)
     |████████████████████████████████| 184 kB 6.4 MB/s
Collecting multivolumefile<0.3.0,>=0.2.0
  Downloading multivolumefile-0.2.2-py3-none-any.whl (16 kB)
Collecting ppmd-cffi<0.4.0,>=0.3.1
  Downloading ppmd-cffi-0.3.3.tar.gz (448 kB)
     |████████████████████████████████| 448 kB 6.4 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python39\python.exe' 'c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\1\AppData\Local\Temp\tmpx_djapyy'
         cwd: C:\Users\1\AppData\Local\Temp\pip-install-rs3z2zck\ppmd-cffi_bfbf06f913dd4b54b551111bc86d5c1d
    Complete output (44 lines):
    Traceback (most recent call last):
      File "c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\overlay\Lib\site-packages\setuptools\build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 3, in <module>
        setup(use_scm_version={"local_scheme": "no-local-version"},
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\python39\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\overlay\Lib\site-packages\setuptools\dist.py", line 434, in __init__
        _Distribution.__init__(self, {
      File "c:\python39\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\overlay\Lib\site-packages\setuptools\dist.py", line 743, in finalize_options
        ep(self)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\overlay\Lib\site-packages\setuptools\dist.py", line 750, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\normal\Lib\site-packages\cffi\setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\normal\Lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\normal\Lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/ffi_build.py", line 76, in <module>
        ffibuilder.cdef('typedef struct CPpmd_State_ * CPpmd_State_Ref;')
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\normal\Lib\site-packages\cffi\api.py", line 112, in cdef
        self._cdef(csource, override=override, packed=packed, pack=pack)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\normal\Lib\site-packages\cffi\api.py", line 126, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\normal\Lib\site-packages\cffi\cparser.py", line 389, in parse
        self._internal_parse(csource)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\normal\Lib\site-packages\cffi\cparser.py", line 431, in _internal_parse
        self._declare('typedef ' + decl.name, realtype, quals=quals)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-0yjv851p\normal\Lib\site-packages\cffi\cparser.py", line 568, in _declare
        raise FFIError(
    cffi.FFIError: multiple declarations of typedef CPpmd_State_Ref (for interactive usage, try cdef(xx, override=True))
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/03/bd/1bb0235398e454f30006bec605f4ce0cb286e00f6d42e1e67a8906cb4627/ppmd-cffi-0.3.3.tar.gz#sha256=e07f79f0de07d8d26387c75087258b8e33d812c4e58856db8ed0dc6b686a8c07 (from https://pypi.org/simple/ppmd-cffi/). Command errored out with exit status 1: 'c:\python39\python.exe' 'c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\1\AppData\Local\Temp\tmpx_djapyy' Check the logs for full command output.
  Downloading ppmd-cffi-0.3.2.tar.gz (447 kB)
     |████████████████████████████████| 447 kB ...
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python39\python.exe' 'c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\1\AppData\Local\Temp\tmp97vbubll'
         cwd: C:\Users\1\AppData\Local\Temp\pip-install-rs3z2zck\ppmd-cffi_6f4365cc988640bf8f79fe9cfff3be07
    Complete output (44 lines):
    Traceback (most recent call last):
      File "c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\overlay\Lib\site-packages\setuptools\build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 3, in <module>
        setup(use_scm_version={"local_scheme": "no-local-version"},
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\python39\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\overlay\Lib\site-packages\setuptools\dist.py", line 434, in __init__
        _Distribution.__init__(self, {
      File "c:\python39\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\overlay\Lib\site-packages\setuptools\dist.py", line 743, in finalize_options
        ep(self)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\overlay\Lib\site-packages\setuptools\dist.py", line 750, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\normal\Lib\site-packages\cffi\setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\normal\Lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\normal\Lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/ffi_build.py", line 76, in <module>
        ffibuilder.cdef('typedef struct CPpmd_State_ * CPpmd_State_Ref;')
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\normal\Lib\site-packages\cffi\api.py", line 112, in cdef
        self._cdef(csource, override=override, packed=packed, pack=pack)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\normal\Lib\site-packages\cffi\api.py", line 126, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\normal\Lib\site-packages\cffi\cparser.py", line 389, in parse
        self._internal_parse(csource)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\normal\Lib\site-packages\cffi\cparser.py", line 431, in _internal_parse
        self._declare('typedef ' + decl.name, realtype, quals=quals)
      File "C:\Users\1\AppData\Local\Temp\pip-build-env-i0sipun4\normal\Lib\site-packages\cffi\cparser.py", line 568, in _declare
        raise FFIError(
    cffi.FFIError: multiple declarations of typedef CPpmd_State_Ref (for interactive usage, try cdef(xx, override=True))
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e7/d1/c4a7bab047ef50579f797845814c69dfd416954398b3861633b40c1275d1/ppmd-cffi-0.3.2.tar.gz#sha256=1120b9f8257a322bc3e064f73cd25c01f9d28e668b0360c1672e77e94d978129 (from https://pypi.org/simple/ppmd-cffi/). Command errored out with exit status 1: 'c:\python39\python.exe' 'c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\1\AppData\Local\Temp\tmp97vbubll' Check the logs for full command output.
Collecting py7zr!=0.10.0,>=0.9.9
  Downloading py7zr-0.14.1-py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB ...
  Downloading py7zr-0.14.0-py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB ...
  Downloading py7zr-0.13.1-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB ...
Collecting zstandard
  Downloading zstandard-0.15.2-cp39-cp39-win32.whl (495 kB)
     |████████████████████████████████| 495 kB 6.8 MB/s
Collecting multivolumefile<0.2.0,>=0.1.1
  Downloading multivolumefile-0.1.4-py3-none-any.whl (15 kB)
Collecting py7zr!=0.10.0,>=0.9.9
  Downloading py7zr-0.13.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 4.8 MB/s
  Downloading py7zr-0.12.0-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB ...
  Downloading py7zr-0.11.3-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 4.5 MB/s
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB ...
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB ...
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB ...
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 6.4 MB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB ...
Installing collected packages: urllib3, texttable, pyparsing, pycryptodome, idna, chardet, certifi, wheel, requests, py7zr, packaging, aqtinstall
Successfully installed aqtinstall-1.1.4 certifi-2020.12.5 chardet-4.0.0 idna-2.10 packaging-20.9 py7zr-0.11.3 pycryptodome-3.10.1 pyparsing-2.4.7 requests-2.25.1 texttable-1.6.3 urllib3-1.26.4 wheel-0.36.2
```

**Comment by pzhlkj6612** [comment]
@lebarsfa Hi. Did you run aqtinstall in VS dev prompt? Open a clean CMD or PowerShell and try again.

**Comment by miurahr** [comment]
We need to wait for upstream new release, py7zr v0.15.1.

**Comment by miurahr** [comment]
- [py7zr v0.15.1](https://pypi.org/project/py7zr/)
- [ppmd-cffi v0.4.1](https://pypi.org/project/ppmd-cffi/)
- [bcj-cffi v0.5.1](https://pypi.org/project/bcj-cffi/)

Now all upstream released with 32bit binaries and dependencies update.

Your trial use ppmd-cffi v0.3.2 that py7zr v0.15.0 depends  has a bug that does not work on x86 32bit platform you observed. py7zr v0.15.1 depends ppmd-cffi > v0.4.0

**Comment by pzhlkj6612** [comment]
Hi @lebarsfa . I noticed that you said in the first comment:

> ... they can easily get Qt Creator+Qt SDK 5.15.2 for MinGW 8.1.0 64 bit.

You and your students are on 64-bit Windows, right? Which architecture of Python 3.9 are you using?

**Comment by pzhlkj6612** [comment]
@lebarsfa OK, got it. Thanks for your reply. :)

**Comment by miurahr** [comment]
Resolved.
