### ISSUE TITLE
Cannot install android on Linux

### ISSUE THREAD

**Issue by EndrII** [miurahr/aqtinstall#255]
i use command from example 
```bash
aqt install 6.1.0 linux android android_arm64_v8a -m all
```
Output
```bash
2021-06-03 14:48:01,675 - aqt - INFO - aqtinstall(aqt) v0.10.1 on Python 3.6.9 [CPython GCC 8.4.0]
2021-06-03 14:48:01,675 - aqt - WARNING - Specified Qt version is unknown: 6.1.0.
2021-06-03 14:48:01,823 - aqt - ERROR - Specified packages are not found while parsing XML of package information!
2021-06-03 14:48:01,823 - aqt - DEBUG - <Updates>
 <ApplicationName>{AnyApplication}</ApplicationName>
 <ApplicationVersion>1.0.0</ApplicationVersion>
 <Checksum>true</Checksum>
 <PackageUpdate>
  <Name>qt.qt6.610.android</Name>
  <DisplayName>Android</DisplayName>
  <Description>Qt 6.1.0 Prebuilt Components for Android armv7, arm64-v8a, x86 and x86_64</Description>
  <Version>6.1.0-0-202105040943</Version>
  <ReleaseDate>2021-05-04</ReleaseDate>
  <Dependencies>qt.tools.qtcreator, qt.qt6.610.doc, qt.qt6.610.examples, qt.qt6.610.android_arm64_v8a, qt.qt6.610.android_armv7, qt.qt6.610.android_x86, qt.qt6.610.android_x86_64</Dependencies>
  <AutoDependOn/>
  <Default>false</Default>
  <Script>installscript.qs</Script>
  <SortingPriority>270</SortingPriority>
  <DownloadableArchives/>
  <UpdateFile CompressedSize="0" UncompressedSize="0" OS="Any"/>
  <SHA1>84f4c75b3d3c7da9c2f9fd56ad31c024876c8a32</SHA1>
 </PackageUpdate>
 <SHA1>84f4c75b3d3c7da9c2f9fd56ad31c024876c8a32</SHA1>
 <MetadataName>2021-05-04-0944_meta.7z</MetadataName>
</Updates>

Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/aqt/__init__.py", line 38, in main
    return cli.run()
  File "/usr/local/lib/python3.6/dist-packages/aqt/installer.py", line 373, in run
    return args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/aqt/installer.py", line 186, in run_install
    finisher(target_config, base_dir, self.logger)
  File "/usr/local/lib/python3.6/dist-packages/aqt/installer.py", line 460, in finisher
    raise e
  File "/usr/local/lib/python3.6/dist-packages/aqt/installer.py", line 445, in finisher
    with open(os.path.join(base_dir, qt_version, arch_dir, 'bin', 'qt.conf'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/storage/Qt/6.1.0/android_arm64_v8a/bin/qt.conf'
```

**Comment by EndrII** [comment]
aqtinstall           1.1.6

**Comment by ddalcino** [comment]
> Output
> 
> ```shell
> 2021-06-03 14:48:01,675 - aqt - INFO - aqtinstall(aqt) v0.10.1 on Python 3.6.9 [CPython GCC 8.4.0]
> ```

This line makes it look like you're using v0.10.1. Can you please try again with the current version?

**Comment by EndrII** [comment]
@ddalcino thanks all is works correctly after update.
