### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by martinrotter** [miurahr/aqtinstall#275]
```
 Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\aqt.exe\__main__.py", line 7, in <module>
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\__init__.py", line 31, in main
    return cli.run()
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\installer.py", line 675, in run
    result = args.func(args)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\installer.py", line 437, in run_tool
    timeout=timeout,
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\archives.py", line 365, in __init__
    os_name, "desktop", version, arch, base, timeout=timeout
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\archives.py", line 174, in __init__
    self._get_archives()
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\archives.py", line 375, in _get_archives
    self._parse_update_xml(archive_url, [])
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\archives.py", line 395, in _parse_update_xml
    if not full_version.base_version == self.version.base_version:
AttributeError: 'Version' object has no attribute 'base_version'a
```

Used command: `aqt tool windows tools_openssl_x64 1.1.1 qt.tools.openssl.win_x64` but it does not happen on my home PC, only on Github runner/actions. It has something to do with deps versions maybe?

**Comment by miurahr** [comment]
@MartinDelille Thank you for report! Does #276 fix your case?

**Comment by martinrotter** [comment]
@miurahr How do I test?

**Comment by miurahr** [comment]
OK, I can reproduce it and fix it in my local.
I'd like to release next patch version and you can test it.

**Comment by martinrotter** [comment]
works now
