### ISSUE TITLE
Failed to install Qt 6.2 on macOS

### ISSUE THREAD

**Issue by moodyhunter** [miurahr/aqtinstall#288]
It says 

```
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/aqt/__init__.py", line 31, in main
    return cli.run()
  File "/usr/local/lib/python3.9/site-packages/aqt/installer.py", line 675, in run
    result = args.func(args)
  File "/usr/local/lib/python3.9/site-packages/aqt/installer.py", line 285, in run_install
    Updater.update(target_config, base_dir)
  File "/usr/local/lib/python3.9/site-packages/aqt/updater.py", line 298, in update
    raise e
  File "/usr/local/lib/python3.9/site-packages/aqt/updater.py", line 270, in update
    updater.set_license(base_dir, target.version, arch_dir)
  File "/usr/local/lib/python3.9/site-packages/aqt/updater.py", line 217, in set_license
    with open(
FileNotFoundError: [Errno 2] No such file or directory: './testQt/6.2.0/clang_64/mkspecs/qconfig.pri'
```

aqtinstall version 1.2.1, and the command is `aqt install -O ./testQt 6.2.0 mac desktop` 

In Qt 6.2 the installed files are not in `./testQt/6.2.0/clang_64` but `./testQt/6.2.0/macos` instead.

**Comment by miurahr** [comment]
Did you try command line arch:  replace `clang_64` to `macos`. (default: `clang_64`)?
`aqt install -O ./testQt 6.2.0 mac desktop macos`

Is this also produce same error?

**Comment by moodyhunter** [comment]
it says `NoPackageFound`

```
aqtinstall(aqt) v1.2.1 on Python 3.9.5 [CPython Clang 12.0.0 (clang-1200.0.32.29)]
Specified target combination is not valid or unknown: mac desktop macos
Specified packages are not found while parsing XML of package information!
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/aqt/__init__.py", line 31, in main
    return cli.run()
  File "/usr/local/lib/python3.9/site-packages/aqt/installer.py", line 675, in run
    result = args.func(args)
  File "/usr/local/lib/python3.9/site-packages/aqt/installer.py", line 250, in run_install
    qt_archives = QtArchives(
  File "/usr/local/lib/python3.9/site-packages/aqt/archives.py", line 174, in __init__
    self._get_archives()
  File "/usr/local/lib/python3.9/site-packages/aqt/archives.py", line 213, in _get_archives
    self._parse_update_xml(archive_url, target_packages)
  File "/usr/local/lib/python3.9/site-packages/aqt/archives.py", line 267, in _parse_update_xml
    raise NoPackageFound
aqt.exceptions.NoPackageFound
```

**Comment by miurahr** [comment]
Their (The Qt Foundation) package name seems to be  still like `qt.qt6.620.clang_64` as same as before, but content seems to be extracted into different place other than other platforms and versions.

**Comment by miurahr** [comment]
Is #289 working for @moodyhunter ?
A CI log looks good.

https://dev.azure.com/miurahr/892bc5d7-3681-4359-bd29-fe00ca91ef10/_apis/build/builds/4276/logs/62
```
2021-07-01T04:53:48.6272060Z 2021-07-01 04:53:48,622 - aqt.updater - INFO - updater 4603815360 Patching /Users/runner/work/1/b/Qt/6.2.0/macos/bin/qmake
```

**Comment by moodyhunter** [comment]
Thanks, @miurahr, PR #289 fixed this problem, it now works well with Qt 6.2 on my mac machine.

**Comment by Aksem** [comment]
@miurahr , may I or could you make this change from 6.1.2 instead of 6.2.0? Because I have the same problem with 6.1.2 and cannot migrate to 6.2.0 because PySide6 supports only 6.1.2.

**Comment by miurahr** [comment]
v1.2.4 out with your patch.
