### ISSUE TITLE
2019 winrt builds are broken :(

### ISSUE THREAD

**Issue by danryu** [miurahr/aqtinstall#310]
When I execute 
`aqt install 5.15.2 windows winrt win64_msvc2019_winrt_x86`
OR
`aqt install 5.15.2 windows winrt win64_msvc2019_winrt_x64`
on either Linux or Windows, the installation fails with:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/test/5.15.2/msvc2019_winrt_x64/mkspecs/qconfig.pri'`

This is because the actual directory path is:
**/home/test/5.15.2/winrt_x64_msvc2019/mkspecs/qconfig.pri**

```
test@hp14:~$ ls -al /home/test/5.15.2/winrt_x64_msvc2019/mkspecs/qconfig.pri 
-rw-r--r-- 1 test test 963 Nov 12  2020 /home/test/5.15.2/winrt_x64_msvc2019/mkspecs/qconfig.pri
```

Example traceback on Windows:
```
2021-07-12T18:17:47.4968319Z Traceback (most recent call last):
2021-07-12T18:17:47.4969363Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\runpy.py", line 193, in _run_module_as_main
2021-07-12T18:17:47.4970108Z     "__main__", mod_spec)
2021-07-12T18:17:47.4970793Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\runpy.py", line 85, in _run_code
2021-07-12T18:17:47.4971472Z     exec(code, run_globals)
2021-07-12T18:17:47.4972306Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\aqt.exe\__main__.py", line 7, in <module>
2021-07-12T18:17:47.4973316Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\__init__.py", line 31, in main
2021-07-12T18:17:47.4974012Z     return cli.run()
2021-07-12T18:17:47.4974769Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\installer.py", line 675, in run
2021-07-12T18:17:47.4975535Z     result = args.func(args)
2021-07-12T18:17:47.4976323Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\installer.py", line 285, in run_install
2021-07-12T18:17:47.4977181Z     Updater.update(target_config, base_dir)
2021-07-12T18:17:47.4978038Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\updater.py", line 321, in update
2021-07-12T18:17:47.4978741Z     raise e
2021-07-12T18:17:47.4979481Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\updater.py", line 291, in update
2021-07-12T18:17:47.4980366Z     updater.set_license(base_dir, target.version, arch_dir)
2021-07-12T18:17:47.4981286Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\updater.py", line 235, in set_license
2021-07-12T18:17:47.4982252Z     os.path.join(base_dir, qt_version, arch_dir, "mkspecs", "qconfig.pri"), "r+"
2021-07-12T18:17:47.4983171Z FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Qt\\5.15.2\\msvc2019_winrt_x64\\mkspecs\\qconfig.pri'
```

**Comment by miurahr** [comment]
Does a change in #311 work for you?

**Comment by danryu** [comment]
Thanks!
I tried doing a manual patch, but I seem to have another error now - I can't judge if the first one is fixed....

I'll post the whole traceback so you can get an idea of what's going on.

```
tester@hp14:~/test_qt$ aqt install  5.15.2 windows winrt win64_msvc2019_winrt_x64
aqtinstall(aqt) v1.2.2 on Python 3.9.5 [CPython GCC 10.3.0]
Downloading qtbase...
Downloading qtwebchannel...
Downloading qttranslations...
Downloading qtsvg...
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of qtwebchannel-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 3.86922790
Downloading qtmultimedia...
Finished installation of qtsvg-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 4.46899881
Downloading qtdeclarative...
Finished installation of qttranslations-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 4.94983746
Downloading qtgraphicaleffects...
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of qtmultimedia-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 4.78283529
Downloading qtwebsockets...
Finished installation of qtgraphicaleffects-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 3.69875127
Downloading qttools...
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of qtwebsockets-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 3.41539220
Downloading qtimageformats...
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of qtdeclarative-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 22.62518431
Downloading qtsensors...
Finished installation of qtimageformats-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 18.35928330
Downloading qtquickcontrols...
Downloading qt3d...
Finished installation of qtbase-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 33.11511275
Downloading qtconnectivity...
Finished installation of qttools-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 25.97016341
Downloading qtxmlpatterns...
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of qtquickcontrols-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 6.86102334
Downloading qtquickcontrols2...
Finished installation of qtconnectivity-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 4.20966259
Downloading qtscxml...
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of qtxmlpatterns-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 9.19081039
Downloading qtspeech...
Finished installation of qtscxml-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 6.89807419
Downloading qtgamepad...
Finished installation of qt3d-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 13.33291069
Downloading qtwebview...
Redirected: qtproject.mirror.liquidtelecom.com
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of qtspeech-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 3.34935586
Downloading qtremoteobjects...
Finished installation of qtquickcontrols2-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 10.16986200
Finished installation of qtgamepad-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 3.33033766
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of qtwebview-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 3.54453655
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of qtremoteobjects-Windows-Windows_10-MSVC2019-WinRT-WinRT_10-X86_64.7z in 4.48872815
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 385, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.qt.io', port=443): Read timed out. (read timeout=3.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tester/.local/lib/python3.9/site-packages/aqt/helper.py", line 55, in getUrl
    r = requests.get(url, allow_redirects=False, timeout=timeout)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='download.qt.io', port=443): Read timed out. (read timeout=3.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/tester/.local/lib/python3.9/site-packages/aqt/installer.py", line 724, in installer
    hash = binascii.unhexlify(getUrl(hashurl, timeout, logger))
  File "/home/tester/.local/lib/python3.9/site-packages/aqt/helper.py", line 70, in getUrl
    raise ArchiveConnectionError()
aqt.exceptions.ArchiveConnectionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tester/.local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/home/tester/.local/lib/python3.9/site-packages/aqt/__init__.py", line 31, in main
    return cli.run()
  File "/home/tester/.local/lib/python3.9/site-packages/aqt/installer.py", line 675, in run
    result = args.func(args)
  File "/home/tester/.local/lib/python3.9/site-packages/aqt/installer.py", line 283, in run_install
    self.call_installer(qt_archives, base_dir, sevenzip, keep)
  File "/home/tester/.local/lib/python3.9/site-packages/aqt/installer.py", line 688, in call_installer
    pool.starmap(installer, tasks)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
aqt.exceptions.ArchiveConnectionError
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

```

**Comment by danryu** [comment]
Update: it just succeeded with 
`aqt install  5.15.1 windows winrt win64_msvc2019_winrt_x64 -b https://mirrors.ocf.berkeley.edu/qt/`
so likely I am experiencing network issues.
Confirming now with 5.15.2 ...

**Comment by danryu** [comment]
yes, this works fine :)

Any chance of an update soon, so I don't have to patch my CI workflow? ;)

**Comment by miurahr** [comment]
v1.2.3 is out with the fix.

**Comment by danryu** [comment]
I noticed - thanks a lot for the quick turnaround :)
