### ISSUE TITLE
'aqt list tools' is broken - ValueError: Invalid version string: 'tools'

### ISSUE THREAD

**Issue by danryu** [miurahr/aqtinstall#328]
Using aqt 1.2.4 on Linux.
Following documentation at https://aqtinstall.readthedocs.io/en/latest/cli.html 

```
test@hp14:~$ aqt list tools windows desktop 
aqtinstall(aqt) v1.2.4 on Python 3.9.5 [CPython GCC 10.3.0]
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/aqt/__init__.py", line 31, in main
    return cli.run()
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 675, in run
    result = args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 472, in run_list
    pl = PackagesList(qt_version, host, target, Settings.baseurl)
  File "/usr/local/lib/python3.9/dist-packages/aqt/archives.py", line 72, in __init__
    self.version = Version(version)
  File "/home/test/.local/lib/python3.9/site-packages/semantic_version/base.py", line 105, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/home/test/.local/lib/python3.9/site-packages/semantic_version/base.py", line 311, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: 'tools'
test@hp14:~$ aqt list tools linux desktop 
aqtinstall(aqt) v1.2.4 on Python 3.9.5 [CPython GCC 10.3.0]
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/aqt/__init__.py", line 31, in main
    return cli.run()
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 675, in run
    result = args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 472, in run_list
    pl = PackagesList(qt_version, host, target, Settings.baseurl)
  File "/usr/local/lib/python3.9/dist-packages/aqt/archives.py", line 72, in __init__
    self.version = Version(version)
  File "/home/test/.local/lib/python3.9/site-packages/semantic_version/base.py", line 105, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/home/test/.local/lib/python3.9/site-packages/semantic_version/base.py", line 311, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: 'tools'

```

**Comment by ddalcino** [comment]
For version 1.2.4, try these docs: https://aqtinstall.readthedocs.io/en/v1.2.4/cli.html

The latest version has made quite a few changes to `aqt list tools`, and the changes aren't finished yet.

**Comment by ddalcino** [comment]
Maybe the readme should link to the docs for 1.2.4 until version 2.0 is released?

**Comment by danryu** [comment]
Thanks for the link to the previous docs, but the commands there don't work either.
Taken from https://aqtinstall.readthedocs.io/en/v1.2.4/cli.html?highlight=tools#command-examples :

```
test@hp14:~$ aqt tool linux tools_ifw 4.1 qt.tools.ifw.41
Specified target combination is not valid: linux tools_ifw qt.tools.ifw.41
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/aqt/__init__.py", line 31, in main
    return cli.run()
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 675, in run
    result = args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 431, in run_tool
    tool_archives = ToolArchives(
  File "/usr/local/lib/python3.9/dist-packages/aqt/archives.py", line 365, in __init__
    super(ToolArchives, self).__init__(
  File "/usr/local/lib/python3.9/dist-packages/aqt/archives.py", line 141, in __init__
    self.version = Version(version)
  File "/home/test/.local/lib/python3.9/site-packages/semantic_version/base.py", line 105, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/home/test/.local/lib/python3.9/site-packages/semantic_version/base.py", line 311, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '4.1'
test@hp14:~$ aqt tool windows tools_vcredist 2019-02-13-1 qt.tools.vcredist_msvc2019_x64
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/aqt/__init__.py", line 31, in main
    return cli.run()
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 675, in run
    result = args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 431, in run_tool
    tool_archives = ToolArchives(
  File "/usr/local/lib/python3.9/dist-packages/aqt/archives.py", line 365, in __init__
    super(ToolArchives, self).__init__(
  File "/usr/local/lib/python3.9/dist-packages/aqt/archives.py", line 141, in __init__
    self.version = Version(version)
  File "/home/test/.local/lib/python3.9/site-packages/semantic_version/base.py", line 105, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/home/test/.local/lib/python3.9/site-packages/semantic_version/base.py", line 311, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '2019-02-13-1'
```
Is anybody able to run any tools commands on any version, anywhere?
This is a blocker for me as I can't install any necessary build deps for Windows x64 (cmake, vcredist),

**Comment by ddalcino** [comment]
Yes. The master branch at HEAD has been capable of installing tools properly for a long time. The prereleases should probably work as well; the latest one is here: https://github.com/miurahr/aqtinstall/releases/tag/v2.0.0b3. Don't get too comfortable with the interface yet, it's not stable yet.

If you're using this tool in your CI, you can use https://github.com/jurplel/install-qt-action. It's locked to an older version of aqtinstall, and it installs ifw just fine.

**Comment by danryu** [comment]
Thanks for the tips.

So is everything but HEAD and the pre-releases not expected to be working?

I managed to get 1 valid version combination to work for tools_cmake:
`aqt tool  windows tools_cmake 3.19.2-202101071154 qt.tools.cmake.win64`

But all attempts at installing tools_vcredist have failed. Despite carefully following the working example and using the Updates.xml at https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_vcredist/Updates.xml as a reference, I could not get any version combination to work:
```
  aqt tool windows tools_vcredist 2019-02-13-1 qt.tools.vcredist_msvc2019_x64
  aqt tool windows tools_vcredist 2019-02-13-1 qt.tools.vcredist_msvc2019_x64
  aqt tool windows tools_vcredist 2020-05-19-1  qt.tools.vcredist_msvc2019_x64
  aqt tool windows tools_vcredist_x64 2020-05-19-1  qt.tools.vcredist_msvc2019_x64
  aqt tool windows tools_vcredist_x64 2020-03-18  qt.tools.vcredist_msvc2019_x64
  aqt tool windows tools_vcredist 2020-03-18  qt.tools.vcredist_msvc2019_x64
  aqt tool windows tools_vcredist 2020-03-18 qt.tools.vcredist_64
  aqt tool windows tools_vcredist 2011-03-03-1  qt.tools.vcredist
```

all fail with:
`ValueError: Invalid version string: '<version_passed>'`

**Comment by ddalcino** [comment]
No. Master at HEAD and all of the pre-releases are expected to be working. The [jurplel GH Action](https://github.com/jurplel/install-qt-action) is working.

The command line interface for HEAD and the pre-releases is expected to change before the release of version 2.0, so don't use them in your CI/CD yet.

If you want something more current to work, you can git checkout master.

**Comment by danryu** [comment]
Seems like pre-releases aren't working either:

```
test@hp14:~$ aqt version
aqtinstall(aqt) v2.0.0b3 on Python 3.9.5 [CPython GCC 10.3.0]
test@hp14:~$ aqt tool windows tools_vcredist 2019-02-13-1 qt.tools.vcredist_msvc2019_x64
aqtinstall(aqt) v2.0.0b3 on Python 3.9.5 [CPython GCC 10.3.0]
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/aqt/__init__.py", line 31, in main
    return cli.run()
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 801, in run
    result = args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 442, in run_tool
    tool_archives = ToolArchives(
  File "/usr/local/lib/python3.9/dist-packages/aqt/archives.py", line 322, in __init__
    super(ToolArchives, self).__init__(
  File "/usr/local/lib/python3.9/dist-packages/aqt/archives.py", line 85, in __init__
    self.version = Version(version_str)
  File "/usr/local/lib/python3.9/dist-packages/aqt/metadata.py", line 86, in __init__
    raise ValueError("Invalid version string: '{}'".format(version_string))
ValueError: Invalid version string: '2019-02-13-1'
test@hp14:~$ aqt tool windows tools_vcredist 2020-05-19-1  qt.tools.vcredist_msvc2019_x64 
aqtinstall(aqt) v2.0.0b3 on Python 3.9.5 [CPython GCC 10.3.0]
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/aqt/__init__.py", line 31, in main
    return cli.run()
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 801, in run
    result = args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/aqt/installer.py", line 442, in run_tool
    tool_archives = ToolArchives(
  File "/usr/local/lib/python3.9/dist-packages/aqt/archives.py", line 322, in __init__
    super(ToolArchives, self).__init__(
  File "/usr/local/lib/python3.9/dist-packages/aqt/archives.py", line 85, in __init__
    self.version = Version(version_str)
  File "/usr/local/lib/python3.9/dist-packages/aqt/metadata.py", line 86, in __init__
    raise ValueError("Invalid version string: '{}'".format(version_string))
ValueError: Invalid version string: '2020-05-19-1'

```

**Comment by ddalcino** [comment]
You are right; I was wrong. I had forgotten that the `aqt tool` feature was still experimental; it is listed as such in the docs.

The `aqt tool` feature works properly right now for all of the tools except for `tools_vcredist`, `tools_conan`, and the `qt.tools.windows_kits_debuggers` package in `tools_qtcreator`. This is because the Updates.xml files at the Qt repo contain dates in the 'Version' tags and not versions, but only for those three tools. The current version expects the 'Version' tag to contain a semantic version, and it fails when it reads a date. I'm not sure if any version of aqt has ever been able to install those tools. This tool is being redesigned for the next version, and the new version should no longer be experimental.

I have two recommendations for you:
1. Try using version 1.1.3. That's the version that the jurplel action uses, and I'm certain that it was before aqt started parsing versions in the 'Version' tags. I don't know if this will work or not, but it's a good place to start.
2. Try using https://github.com/miurahr/aqtinstall/pull/299. The interface is a little different, and it's not done yet, but it does install vcredist properly: https://github.com/miurahr/aqtinstall/pull/299#issuecomment-877729856. Please note that the command `aqt tool windows desktop tools_vcredist` will install EVERY version of vcredist in the repo, which is probably not what you want.

**Comment by ddalcino** [comment]
I just tried the branch https://github.com/miurahr/aqtinstall/tree/releases/0.11, and vcredist installed ok:

```
$python3 -m aqt tool windows tools_vcredist 2019-02-13-1 qt.tools.vcredist_msvc2019_x64
2021-07-20 10:38:27,834 - aqt - INFO - aqtinstall(aqt) v1.2.3.dev93 on Python 3.6.9 [CPython GCC 8.4.0]
2021-07-20 10:38:28,601 - aqt - WARNING - Version 2020-05-19-1 differ from requested version 2019-02-13-1 -- skip.
2021-07-20 10:38:28,658 - aqt - INFO - Finished installation
2021-07-20 10:38:28,661 - aqt - INFO - Time elapsed: 0.83678790 second
```

**Comment by danryu** [comment]
Thanks, I was able to install from #299 by doing a
`pip install git+https://github.com/miurahr/aqtinstall.git@topic-tool-latest`

after which I was able to install vcredist successfully.

```
$ aqt tool windows desktop -O Qt/ tools_vcredist qt.tools.vcredist_msvc2019_x64
aqtinstall(aqt) v2.0.0b4.dev13 on Python 3.9.5 [CPython GCC 10.3.0]
Downloading qt.tools.vcredist_msvc2019_x64...
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of vcredist_msvc2019_x64.7z in 15.71920621
Finished installation
Time elapsed: 17.82708050 second
```

I still get a warning on installing cmake, but it seems to work anyway....
```
$ aqt tool windows desktop -O Qt/ tools_cmake qt.tools.cmake.win64
aqtinstall(aqt) v2.0.0b4.dev13 on Python 3.9.5 [CPython GCC 10.3.0]
**Specified target combination is not valid: windows tools_cmake qt.tools.cmake.win64**
Downloading qt.tools.cmake.win64...
Redirected: qtproject.mirror.liquidtelecom.com
Finished installation of windows64_x64_cmake_tools.7z in 19.30505920
Finished installation
Time elapsed: 20.85347223 second
```

**Comment by miurahr** [comment]
Yes, improvement for warning part is progressed on #318 by @ddalcino 
Thank @danryu for feedback!

**Comment by miurahr** [comment]
v2.0.0b5 out with the improvement.
