### ISSUE TITLE
ci/generate_combinations.json failed with metadata.py module

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#342]
CI failed with categories error.

metadata.MetadataFactory class accept "qt" and "tool" but CI tool call with "qt5" and "qt6".

It seems to be caused by modification and refactoring of list subcommand.

```
Fetching arches
Traceback (most recent call last):
  File "ci/generate_combinations.py", line 244, in <module>
    main(filename=json_filename, is_write_file=args.write, is_verbose=args.verbose)
  File "ci/generate_combinations.py", line 176, in main
    actual = [generate_combos(new_archive=expect[0]["new_archive"])]
  File "ci/generate_combinations.py", line 149, in generate_combos
    "qt": merge_records(iter_arches()),
  File "ci/generate_combinations.py", line 137, in merge_records
    for record in arch_records:
  File "ci/generate_combinations.py", line 58, in iter_arches
    archive_ids = list(iter_archive_ids(categories=("qt5", "qt6"), add_extensions=True))
  File "ci/generate_combinations.py", line 53, in iter_archive_ids
    yield ArchiveId(cat, host, target, ext)
  File "/home/runner/work/aqtinstall/aqtinstall/aqt/metadata.py", line 228, in __init__
    raise ValueError("Category '{}' is invalid".format(category))
ValueError: Category 'qt5' is invalid
Error: Process completed with exit code 1.
```

**Comment by ddalcino** [comment]
#343 should resolve the issue.

I think it would be worth adding some test code for the `ci/generate_combinations.py` script; that would prevent this from becoming an issue in the first place. That will have to wait for a future PR.

**Comment by miurahr** [comment]
It still produce an error, after merged.

```
Fetching arches
Traceback (most recent call last):
  File "ci/generate_combinations.py", line 233, in <module>
    main(filename=json_filename, is_write_file=args.write, is_verbose=args.verbose)
  File "ci/generate_combinations.py", line 165, in main
    actual = [generate_combos(new_archive=expect[0]["new_archive"])]
  File "ci/generate_combinations.py", line 138, in generate_combos
    "qt": merge_records(iter_arches()),
  File "ci/generate_combinations.py", line 126, in merge_records
    for record in arch_records:
  File "ci/generate_combinations.py", line 66, in iter_arches
    for arch_name in MetadataFactory(
  File "/home/runner/work/aqtinstall/aqtinstall/aqt/metadata.py", line 409, in getList
    return self._action()
  File "/home/runner/work/aqtinstall/aqtinstall/aqt/metadata.py", line 402, in <lambda>
    self._to_version(architectures_ver)
  File "/home/runner/work/aqtinstall/aqtinstall/aqt/metadata.py", line 560, in _to_version
    raise CliInputError(msg)
aqt.exceptions.CliInputError: There is no latest version of Qt with the criteria 'qt/linux/desktop'
```

**Comment by ddalcino** [comment]
I can see the failed run here: https://github.com/miurahr/aqtinstall/runs/3162389027?check_suite_focus=true

Unfortunately, I can't reproduce this error, either locally or in CI. I mad a new branch, made an non-meaningful commit to trigger another run of the workflow, and I got this successful run of the workflow: https://github.com/ddalcino/aqtinstall/runs/3162638000?check_suite_focus=true

Can you re-trigger the workflow, and tell me what happens?

**Comment by miurahr** [comment]
When re-run a job, it works.
