### ISSUE TITLE
Memory error is occurred when running aqt install-qt windows desktop 6.2.0 on 32bit python on windows

### ISSUE THREAD

**Issue by martinrotter** [miurahr/aqtinstall#436]
```
 λ aqt list-qt windows desktop --modules 6.2.0 win64_msvc2019_64
debug_info qt3d qt5compat qtactiveqt qtcharts qtconnectivity qtdatavis3d qtimageformats qtlottie qtmultimedia qtnetworkauth qtpositioning qt

quick3d qtquicktimeline qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtshadertools qtvirtualkeyboard qtwebchannel qtwebengine

qtwebsockets qtwebview

 /cygdrive/c/Users/rotter/Downloads/PraktikSW.Praktik.cz  chyba ❗
 λ aqt install-qt --outputdir C:\\Qt windows desktop 6.2.0 win64_msvc2019_64 -m qtwebengine qtmultimedia qtwebchannel qt5compat qtimageformats
aqtinstall(aqt) v2.0.0 on Python 3.8.3 [CPython MSC v.1925 32 bit (Intel)]
Downloading qtimageformats...
Downloading qtmultimedia...
Downloading qtwebchannel...
Downloading qtwebengine...
Redirected: ftp.fau.de
Redirected: ftp.fau.de
Redirected: ftp.fau.de
Redirected: ftp.fau.de
Finished installation of qtwebchannel-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 0.60492760
Downloading qt5compat...
Finished installation of qtimageformats-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 0.89102150
Downloading qtbase...
Finished installation of qtmultimedia-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 0.97993880
Downloading qtsvg...
Redirected: ftp.fau.de
Redirected: ftp.fau.de
Redirected: ftp.fau.de
Finished installation of qt5compat-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 0.86194740
Downloading qtdeclarative...
Finished installation of qtsvg-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 0.71559730
Downloading qttools...
Redirected: ftp.fau.de
Redirected: ftp.fau.de
Finished installation of qttools-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 19.06611700
Downloading qttranslations...
Redirected: ftp.fau.de
Finished installation of qttranslations-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.56577150
Downloading d3dcompiler_47...
Redirected: ftp.fau.de
Finished installation of d3dcompiler_47-x64.7z in 1.16161100
Downloading opengl32sw...
Redirected: ftp.fau.de
Finished installation of qtbase-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 23.20178640
Finished installation of opengl32sw-64-mesa_11_2_2-signed.7z in 3.37533860

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\programy\python\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\programy\python\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "c:\programy\python\lib\site-packages\aqt\installer.py", line 893, in installer
    szf.extractall(path=base_dir)
  File "c:\programy\python\lib\site-packages\py7zr\py7zr.py", line 948, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "c:\programy\python\lib\site-packages\py7zr\py7zr.py", line 604, in _extract
    self.worker.extract(
  File "c:\programy\python\lib\site-packages\py7zr\py7zr.py", line 1165, in extract
    self.extract_single(
  File "c:\programy\python\lib\site-packages\py7zr\py7zr.py", line 1276, in extract_single
    raise e
  File "c:\programy\python\lib\site-packages\py7zr\py7zr.py", line 1261, in extract_single
    crc32 = self.decompress(fp, f.folder, ofp, f.uncompressed, f.compressed, src_end)
  File "c:\programy\python\lib\site-packages\py7zr\py7zr.py", line 1313, in decompress
    tmp = decompressor.decompress(fp, out_remaining)
  File "c:\programy\python\lib\site-packages\py7zr\compressor.py", line 630, in decompress
    tmp = self._decompress(self._unused + data, max_length)
  File "c:\programy\python\lib\site-packages\py7zr\compressor.py", line 602, in _decompress
    data = decompressor.decompress(data)
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\programy\python\lib\site-packages\aqt\installer.py", line 99, in run
    args.func(args)
  File "c:\programy\python\lib\site-packages\aqt\installer.py", line 294, in run_install_qt
    run_installer(qt_archives.get_packages(), base_dir, sevenzip, keep)
  File "c:\programy\python\lib\site-packages\aqt\installer.py", line 835, in run_installer
    pool.starmap(installer, tasks)
  File "c:\programy\python\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "c:\programy\python\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
MemoryError
Arguments: `['C:\\Programy\\Python\\Scripts\\aqt', 'install-qt', '--outputdir', 'C:\\Qt', 'windows', 'desktop', '6.2.0', 'win64_msvc2019_64'

, '-m', 'qtwebengine', 'qtmultimedia', 'qtwebchannel', 'qt5compat', 'qtimageformats']` Host: `uname_result(system='Windows', node='PC-MARTIN

', release='10', version='10.0.19041', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 13, GenuineIntel')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
Please remember to include a copy of this program's output in your report.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\programy\python\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Přesměrování bylo ukončeno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programy\python\lib\threading.py", line 932, in _bootstrap_inner
Exception ignored in: <function Pool.__del__ at 0x04BA86A0>
Traceback (most recent call last):
  File "c:\programy\python\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "c:\programy\python\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\programy\python\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\programy\python\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] Neplatný popisovač
```

**Comment by ddalcino** [comment]
I tried to reproduce this error locally, using Python 3.10 32-bit on Windows, and I think I have narrowed it down to the `qtwebengine` module. Every time I try to install that file, I get a `MemoryError`, sometimes preceded by `SystemError: deallocated bytearray object has exported buffers`.

The qtwebengine file is here, for future reference: https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt6_620/qt.qt6.620.addons.qtwebengine.win64_msvc2019_64/6.2.0-0-202109261527qtwebengine-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z
I tried to extract the file using the standalone `py7zr` tool, and I always get this error:

```console
> python -m py7zr x D:\Downloads\6.2.0-0-202109261527qtwebengine-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z
SystemError: deallocated bytearray object has exported buffers
Traceback (most recent call last):
  File "D:\Users\dave\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\dave\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\__main__.py", line 29, in <module>
    sys.exit(main())
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\__main__.py", line 25, in main
    return cli.Cli().run()
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\cli.py", line 99, in run
    return args.func(args)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\cli.py", line 358, in run_extract
    a.extractall(callback=cb)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 955, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 613, in _extract
    self.worker.extract(
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 1172, in extract
    self.extract_single(
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 1283, in extract_single
    raise e
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 1268, in extract_single
    crc32 = self.decompress(fp, f.folder, ofp, f.uncompressed, f.compressed, src_end)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 1320, in decompress
    tmp = decompressor.decompress(fp, out_remaining)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\compressor.py", line 648, in decompress
    res = self._buf[self._pos :] + tmp[: max_length - current_buf_len]
MemoryError
```

Note that this error is specific to 32-bit Python; I cannot reproduce the error with 64-bit Python.

I am going to open an issue in the `py7zr` repo to track this.

I am skeptical that this is an out-of-memory error, and I think we should consider changing our error messages. I watched both `py7zr` and `aqt` try to unpack this file in Task Manager, and I never saw memory usage go over 880 MB. The file itself is 141MB compressed, and ~643MB decompressed. I am unclear on why py7zr is using so much memory; is it holding the entire uncompressed archive in memory at once?

**Comment by miurahr** [comment]
@martinrotter @ddalcino could you test it again with a small modification of aqtinstall?


Change installer.py#L395 from
```
        with py7zr.SevenZipFile(archive, "r") as szf:
            szf.extractall(path=base_dir)
```

to 

```
        with py7zr.SevenZipFile(archive, "r", blocksize=32768) as szf:
            szf.extractall(path=base_dir)
```

This parameter forces `py7zr`  to set memory buffer size 32KB instead of  default, 1MB.

**Comment by ddalcino** [comment]
> @martinrotter @ddalcino could you test it again with a small modification of aqtinstall?
> 
> Change installer.py#L395 from
> 
> ```diff
> -        with py7zr.SevenZipFile(archive, "r") as szf:
> +        with py7zr.SevenZipFile(archive, "r", blocksize=32768) as szf:
>             szf.extractall(path=base_dir)
> ```
> 
> This parameter forces `py7zr` to set memory buffer size 32KB instead of default, 1MB.

This change still results in a MemoryError for me.

I have noticed that running `py7zr x 6.2.0-0-202109261527qtwebengine-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z` results in a successful decompression, when `blocksize` is set to 32768. Watching `py7zr`'s memory profile in Windows Task Manager shows that it never occupies more than about 40-45MB.

However, running `aqtinstall` with `blocksize=32768`, I can see several child processes spawned by `aqtinstall`, and several of them occupy between 200 and 800 MB each. They use a lot of network bandwidth, and then they write a lot of data to disk, and then they stop doing anything at all, but they still occupy the same amount of space in memory. It looks like they are just taking up space that they don't need, after finishing the decompression. To me, it looks like the one file that takes the longest to download (qtwebengine) gets decompressed last, after all the other files have been decompressed, and at that point, the other processes are all done, but they still occupy ~500MB of memory.

**Comment by miurahr** [comment]
#462 bump py7zr @ v0.17.0 which include a fix for 32bit python.

**Comment by miurahr** [comment]
I've added leak check test as #464.
It report aqtinstall leaks object reference counter.

I've also added leak check for dependency py7zr  at https://github.com/miurahr/py7zr/pull/388 but py7zr does not leak at least for extraction.

**Comment by miurahr** [comment]
I found that `multiprocessing.Pool` parameter `maxtasksperchiled` help force garbage-collect when numbrer of tasks done. #464 tune it when on 32bit python.

**Comment by miurahr** [comment]
Is there any further claims?
