### ISSUE TITLE
Installation of 6.4.0 win64_msvc2019_64 fails on azure devops pipeline runner on windows_2019 image

### ISSUE THREAD

**Issue by theadib** [miurahr/aqtinstall#585]
**Describe the bug**
when I execute
     ` aqt install-qt --outputdir $(Build.BinariesDirectory)\\Qt windows desktop 6.4.0 win64_msvc2019_64 -m all `
the script aborts with disk full exception
But this disk D drive has 12GByte free space before
windows-latest or windows-2022 image do not have  MSVC2019 whereas windows-2019 image has.
So I choose windows-2019 image

**To Reproduce**
  # 1
```
  - script: |
      cd $(Build.BinariesDirectory)
      python -m pip install aqtinstall
      echo "Installing Qt to $(Build.BinariesDirectory)"
      echo "install qt 6.4.0"
      aqt install-qt --outputdir $(Build.BinariesDirectory)\\Qt windows desktop 6.4.0 win64_msvc2019_64 -m all

```
**Expected behavior**

**`aqt` output**
Add program output to help explain your problem.

```
INFO    : aqtinstall(aqt) v3.0.1 on Python 3.10.7 [CPython MSC v.1933 64 bit (AMD64)]
INFO    : Downloading qt3d...
INFO    : Downloading qthttpserver...
INFO    : Downloading qtnetworkauth...
INFO    : Downloading qtquicktimeline...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of qtquicktimeline-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64.7z in 1.48560150
INFO    : Downloading qtshadertools...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of qtshadertools-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64.7z in 1.48801890
INFO    : Downloading qtbase...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of qtdeclarative-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64-debug-symbols.7z in 44.93251080
INFO    : Downloading qttools...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of qtdeclarative-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64.7z in 35.35354360
INFO    : Downloading qttools...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of qttools-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64-debug-symbols.7z in 14.13964240
INFO    : Downloading qt5compat...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of qt5compat-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64-debug-symbols.7z in 2.23388360
INFO    : Finished installation of qtbase-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64.7z in 24.40250470
INFO    : Downloading qtsvg...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of qtsvg-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64.7z in 1.05774990
INFO    : Finished installation of qttools-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64.7z in 8.52346590
INFO    : Downloading qttranslations...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of qttranslations-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64.7z in 1.42207410
INFO    : Downloading d3dcompiler_47...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of d3dcompiler_47-x64.7z in 1.22245150
INFO    : Downloading opengl32sw...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of opengl32sw-64-mesa_11_2_2-signed.7z in 1.74708810
WARNING : Caught OSError, terminating installer workers
ERROR   : [Errno 28] No space left on device
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\site-packages\aqt\installer.py", line 108, in run
    args.func(args)
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\site-packages\aqt\installer.py", line 348, in run_install_qt
    run_installer(qt_archives.get_packages(), base_dir, sevenzip, keep, _archive_dest)
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\site-packages\aqt\installer.py", line 1055, in run_installer
    raise e from e
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\site-packages\aqt\installer.py", line 1031, in run_installer
    pool.starmap(installer, tasks)
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\multiprocessing\pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
OSError: [Errno 28] No space left on device
ERROR   : aqtinstall(aqt) v3.0.1 on Python 3.10.7 [CPython MSC v.1933 64 bit (AMD64)]
Working dir: `D:\a\1\b`
Arguments: `['C:\\hostedtoolcache\\windows\\Python\\3.10.7\\x64\\Scripts\\aqt', 'install-qt', '--outputdir', 'D:\\a\\1\\b\\\\Qt', 'windows', 'desktop', '6.4.0', 'win64_msvc2019_64', '-m', 'all']` Host: `uname_result(system='Windows', node='fv-az182-616', release='10', version='10.0.17763', machine='AMD64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
Please remember to include a copy of this program's output in your report.
##[error]Cmd.exe exited with code '254'.

```

**Desktop (please complete the following information):**
 - windows-2019 image https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md
 - `aqt` version [paste the output from the command `aqt version` or `python -m aqt version`]

**Additional context**

**Comment by ddalcino** [comment]
Please note that when you install any version of Qt with `-m all`, you will have trouble if you don't have lots of free hard disk space. I could be wrong, but I would be surprised if the command you're running works with less than 20GB available, and I wouldn't try it with less than 30GB.

Let's see what you're trying to install:
```console
$ python -m aqt list-qt windows desktop --long-modules 6.4.0 win64_msvc2019_64
   Module Name                        Display Name                     Release Date   Download Size   Installed Size
====================================================================================================================
debug_info          Desktop MSVC 2019 64-bit debug information files   2022-09-27     1.3G            9.7G          
qt3d                Qt 3D Module for MSVC 2019 64-bit                  2022-09-27     7.3M            59.4M         
qt5compat           Qt 5 Compatibility Module for MSVC 2019 64-bit     2022-09-27     1005.1K         5.8M          
qtactiveqt          Active Qt for MSVC 2019 64-bit                     2022-09-27     7.8M            58.1M         
qtcharts            Qt Charts for MSVC 2019 64-bit                     2022-09-27     1.6M            13.4M         
qtconnectivity      Qt Connectivity for MSVC 2019 64-bit               2022-09-27     971.9K          7.4M          
qtdatavis3d         Qt Data Visualization for MSVC 2019 64-bit         2022-09-27     1.1M            8.8M          
qthttpserver        Qt HTTP Server for MSVC 2019 64-bit                2022-09-27     155.6K          836.3K        
qtimageformats      Qt Image Formats for MSVC 2019 64-bit              2022-09-27     715.5K          3.7M          
qtlanguageserver    Qt language Server for MSVC 2019 64-bit            2022-09-27     957.5K          8.5M          
qtlottie            Qt Lottie Animation for MSVC 2019 64-bit           2022-09-27     309.0K          1.9M          
qtmultimedia        Qt Multimedia for MSVC 2019 64-bit                 2022-09-27     12.3M           166.8M        
qtnetworkauth       Qt Network Authorization for MSVC 2019 64-bit      2022-09-27     186.1K          1.1M          
qtpdf               Qt PDF for MSVC 2019 64-bit                        2022-09-27     6.0M            26.0M         
qtpositioning       Qt Positioning for MSVC 2019 64-bit                2022-09-27     953.8K          6.9M          
qtquick3d           Qt Quick 3D for MSVC 2019 64-bit                   2022-09-27     16.5M           146.3M        
qtquick3dphysics    Quick: 3D Physics for MSVC 2019 64-bit             2022-09-27     39.7M           408.7M        
qtquicktimeline     Qt Quick Timeline for MSVC 2019 64-bit             2022-09-27     125.8K          863.1K        
qtremoteobjects     Qt Remote Objects for MSVC 2019 64-bit             2022-09-27     838.9K          4.9M          
qtscxml             Qt State Machine for MSVC 2019 64-bit              2022-09-27     1003.0K         7.1M          
qtsensors           Qt Sensors for MSVC 2019 64-bit                    2022-09-27     546.4K          5.0M          
qtserialbus         Qt SerialBus for MSVC 2019 64-bit                  2022-09-27     487.1K          3.2M          
qtserialport        Qt SerialPort for MSVC 2019 64-bit                 2022-09-27     122.5K          622.6K        
qtshadertools       Qt Shader Tools for MSVC 2019 64-bit               2022-09-27     2.5M            13.7M         
qtspeech            Qt Speech for msvc2019_64-bit                      2022-09-27     363.5K          2.6M          
qtvirtualkeyboard   Qt Virtual Keyboard for MSVC 2019 64-bit           2022-09-27     2.7M            14.4M         
qtwebchannel        Qt WebChannel for MSVC 2019 64-bit                 2022-09-27     247.1K          1.4M          
qtwebengine         Qt WebEngine for MSVC 2019 64-bit                  2022-09-27     162.2M          751.1M        
qtwebsockets        Qt WebSockets for MSVC 2019 64-bit                 2022-09-27     222.0K          1.3M         
```

The first module, `debug_info`, is 9.7 GB installed, and the download size is 1.3 GB. The archive will be downloaded and then unzipped to the install destination. Immediately afterwards, the archive will be deleted. Unfortunately, there will be an instant where both the .7z archive and the decompressed copy of the archive coexist on the hard disk, taking up 11 GB of drive space.

There's also qtwebengine and qtquick3dphysics, which will take up almost 1GB and 0.5GB respectively. If these downloads occur concurrently with debug_info, you're going to blow past 12 GB easily. If you want the installation process to happen quickly without slowing to a near complete standstill, you need twice as much space just to get through this part. This is more a limitation of physics than a limitation of Qt.

I'd say that the real bug here was that aqt asked you to write a bug report, when it should have suggested that you allocate more HDD space.

**Comment by theadib** [comment]
Hello miurahr,

thanks for this clarification.
I removed the -m all and the installation completes without problems.

I will mark this issue for "close with comment".

Sorry for the noise.

Adib.

**Comment by miurahr** [comment]
@theadib it is no problem.
 If we can improve documentation from your experience, please feel free to propose a change.
I think we don't tell anything about storage requirements.
Genuine installer may warn a remaining disk space in UI, and aqtinstall doesn't check it when running.

**Comment by syyyr** [comment]
Just a suggestion: when there's not enough space, aqtinstall says that we should file a bug report. Maybe aqtinstall could check for the no space left error and not print the "please file a bug report" message? (whenever it happens throughout the installation, not before installing anything)

**Comment by ddalcino** [comment]
> Just a suggestion: when there's not enough space, aqtinstall says that we should file a bug report. Maybe aqtinstall could check for the no space left error and not print the "please file a bug report" message? (whenever it happens throughout the installation, not before installing anything)

You are correct. The fact that aqtinstall requests a bug report in this case is a bug. The whole point of the "catch all exceptions and tell users to file bug reports" logic is to help us catch issues like this. IMHO this should never have been closed; I would have tried to fix it but I forgot about it.

That said, I'm not sure how to catch this exception properly. `OSError` is really nonspecific, and likely different on every OS.

@miurahr, can we reopen this?

**Comment by syyyr** [comment]
>That said, I'm not sure how to catch this exception properly. OSError is really nonspecific, and likely different on every OS.

I think it depends on how well https://docs.python.org/3/library/errno.html#errno.ENOSPC is implemented on the various platforms. If it works well, than you could just catch `OSError`, check the `errno` for `ENOSPC` and translate that into some error message. Otherwise just reraise the exception.
