### ISSUE TITLE
New "yaml" dependency

### ISSUE THREAD

**Issue by valveca-ai** [miurahr/aqtinstall#59]
Hello, I'm running a github action to install Qt using https://github.com/jurplel/install-qt-action that uses aqtinstall. Today it started failing with missing "yaml" dependency.

This is the section of the log from the build:

`2019-11-16T23:46:53.9834280Z **[command]pip3 install aqtinstall**
2019-11-16T23:46:55.0888580Z Collecting aqtinstall
2019-11-16T23:46:55.1390690Z   Downloading https://files.pythonhosted.org/packages/3b/1f/0e524bc3f88aef6486b74aabcf8e2e124d6fc29429b463b6d73ac8674173/aqtinstall-0.5.1-py2.py3-none-any.whl
2019-11-16T23:46:55.1943150Z Collecting py7zr
2019-11-16T23:46:55.2003450Z   Downloading https://files.pythonhosted.org/packages/ce/51/cac74f941fa42f483605536bab67c30755e6fa42a9eb909cd0f7d3318a9f/py7zr-0.4.1-py3-none-any.whl
2019-11-16T23:46:55.3388480Z Collecting requests
2019-11-16T23:46:55.3498650Z   Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
2019-11-16T23:46:55.4108900Z Collecting six
2019-11-16T23:46:55.4213330Z   Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
2019-11-16T23:46:55.4666070Z Collecting chardet<3.1.0,>=3.0.2
2019-11-16T23:46:55.4757400Z   Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
2019-11-16T23:46:55.5434390Z Collecting idna<2.9,>=2.5
2019-11-16T23:46:55.5506500Z   Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
2019-11-16T23:46:55.6381030Z Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
2019-11-16T23:46:55.6441500Z   Downloading https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl (125kB)
2019-11-16T23:46:55.7360840Z Collecting certifi>=2017.4.17
2019-11-16T23:46:55.7447140Z   Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
2019-11-16T23:46:55.8013500Z Installing collected packages: py7zr, chardet, idna, urllib3, certifi, requests, six, aqtinstall
2019-11-16T23:46:56.4280560Z Successfully installed aqtinstall-0.5.1 certifi-2019.9.11 chardet-3.0.4 idna-2.8 py7zr-0.4.1 requests-2.22.0 six-1.13.0 urllib3-1.25.7

2019-11-16T23:46:56.6102560Z **[command]python3 -m aqt install -O /Users/runner/runners/2.160.2/work/ts 5.12.5 mac desktop**
2019-11-16T23:46:56.7440920Z Traceback (most recent call last):
2019-11-16T23:46:56.7474380Z   File "/Users/runner/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/runpy.py", line 183, in _run_module_as_main
2019-11-16T23:46:56.7476200Z     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2019-11-16T23:46:56.7476980Z   File "/Users/runner/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/runpy.py", line 142, in _get_module_details
2019-11-16T23:46:56.7484520Z     return _get_module_details(pkg_main_name, error)
2019-11-16T23:46:56.7492620Z   File "/Users/runner/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/runpy.py", line 109, in _get_module_details
2019-11-16T23:46:56.7546670Z     __import__(pkg_name)
2019-11-16T23:46:56.7576070Z   File "/Users/runner/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aqt/__init__.py", line 23, in <module>
2019-11-16T23:46:56.7595650Z     from aqt.cli import Cli
2019-11-16T23:46:56.7623250Z   File "/Users/runner/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aqt/cli.py", line 31, in <module>
**2019-11-16T23:46:56.7630970Z     import yaml
2019-11-16T23:46:56.7660170Z ModuleNotFoundError: No module named 'yaml'**
2019-11-16T23:46:56.7689100Z ##[error]The process 'python3' failed with exit code 1`

Thanks
Bill

**Comment by miurahr** [comment]
Now aqtinstall depneds on pyyaml and requirements.txt has it. but v0.5.1 does not have it in setup.py.

**Comment by miurahr** [comment]
Release v0.5.2 with fix now in PyPI.

**Comment by miurahr** [comment]
I'd like to notify that installation path is changed from '/example/Qt5.12.5/5.12.5/(your_arch)/bin' to '/example/Qt/5.12.5/(your_arch)/bin' as same as GUI installer in version v0.5.x. It is introduced v0.5a2.

https://github.com/miurahr/aqtinstall/commit/03635993597f1d22bf4981ca140acf37b1027492

It would affect a work flow too.
