### ISSUE TITLE
Error installing Qt on Ubuntu 20.04

### ISSUE THREAD

**Issue by gitfactor** [miurahr/aqtinstall#599]
**Describe the bug**
Code threw a bug when installing Qt 5.12

**To Reproduce**
These are the commands I followed. I got the error at the **last command**, in Qt 5.12 section.

> ![image](https://user-images.githubusercontent.com/116884443/198573291-0eec59a1-146d-4254-a8f2-065a7fe22138.png)

**Expected behavior**
I expected the Qt installation to proceed without errors.

**`aqt` output**
Add program output to help explain your problem.
```
:~$ python3 -m aqt install 5.12.11 linux desktop -O /opt/qt -m all
INFO    : aqtinstall(aqt) v3.0.2 on Python 3.8.10 [CPython GCC 9.4.0]
WARNING : The command 'install' is deprecated and marked for removal in a future version of aqt.
In the future, please use the command 'install-qt' instead.
INFO    : Downloading qtquickcontrols...
INFO    : Downloading qtgraphicaleffects...
INFO    : Downloading qttools...
INFO    : Downloading qtbase...
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Downloading qtserialbus...
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Downloading qtremoteobjects...
INFO    : Downloading qtcharts...
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Downloading qtconnectivity...
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Downloading qtgraphicaleffects...
INFO    : Downloading qttools...
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Downloading qtquickcontrols...
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Downloading qtserialbus...
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Downloading qtremoteobjects...
INFO    : Redirected: mirrors.ukfast.co.uk
INFO    : Downloading qtpurchasing...
INFO    : Redirected: mirrors.ukfast.co.uk
WARNING : Caught PermissionError, terminating installer workers
ERROR   : [Errno 13] Permission denied: '/opt/qt'
Traceback (most recent call last):
  File "/home/_username_/.local/lib/python3.8/site-packages/aqt/installer.py", line 108, in run
    args.func(args)
  File "/home/_username_/.local/lib/python3.8/site-packages/aqt/installer.py", line 348, in run_install_qt
    run_installer(qt_archives.get_packages(), base_dir, sevenzip, keep, _archive_dest)
  File "/home/_username_/.local/lib/python3.8/site-packages/aqt/installer.py", line 1058, in run_installer
    raise e from e
  File "/home/_username_/.local/lib/python3.8/site-packages/aqt/installer.py", line 1034, in run_installer
    pool.starmap(installer, tasks)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
PermissionError: [Errno 13] Permission denied: '/opt/qt'
ERROR   : aqtinstall(aqt) v3.0.2 on Python 3.8.10 [CPython GCC 9.4.0]
Working dir: `/home/_username_`
Arguments: `['/home/_username_/.local/lib/python3.8/site-packages/aqt/__main__.py', 'install', '5.12.11', 'linux', 'desktop', '-O', '/opt/qt', '-m', 'all']` Host: `uname_result(system='Linux', node='DYSIS-DEV-001', release='5.15.0-52-generic', version='#58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022', machine='x86_64', processor='x86_64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
```

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04 LTS]
 - aqt version: `aqtinstall(aqt) v3.0.2 on Python 3.8.10 [CPython GCC 9.4.0]`

**Additional context**

**Comment by miurahr** [comment]
You don't have root permission to write `/opt` folder. pls. consider to use `sudo` or `su` to root user.

**Comment by gitfactor** [comment]
Yes, thanks, I worked that out as the issue and fixed it yesterday. However, I couldn't find link to close the issue.

Regards,
Jill McGhee

________________________________

Jill McGhee
Software Engineer

​
​
​
​This e-mail and any attachments is a confidential correspondence intended only for use of DYSIS Medical Limited or the sender as named above. If you are not the intended recipient or the agent responsible for delivering the message to the intended recipient, you are hereby notified that any disclosure, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender by phone or by replying to this message, and then delete this message from your system. Registered office:Octagon Point, 5 Cheapside, London, England, EC2V 6AA. Company Registration Number: 4446534
