### ISSUE TITLE
Android 5.14

### ISSUE THREAD

**Issue by EndrII** [miurahr/aqtinstall#76]
Starting with version 5.14, Android is not divided into a holistic platform. How to install it?

``` bash
aqt install --outputdir /home/andrei/Qt 5.14.0 linux android
 in dir /home/andrei/worker/qtBuilder/qtBuilder/build (timeout 1200 secs)
 watching logfiles {}
 argv: [b'aqt', b'install', b'--outputdir', b'/home/andrei/Qt', b'5.14.0', b'linux', b'android']
 environment:
  DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
  HOME=/home/andrei
  LANG=en_US.UTF-8
  LC_ADDRESS=en_US.UTF-8
  LC_IDENTIFICATION=en_US.UTF-8
  LC_MEASUREMENT=en_US.UTF-8
  LC_MONETARY=en_US.UTF-8
  LC_NAME=en_US.UTF-8
  LC_NUMERIC=en_US.UTF-8
  LC_PAPER=en_US.UTF-8
  LC_TELEPHONE=en_US.UTF-8
  LC_TIME=en_US.UTF-8
  LESSCLOSE=/usr/bin/lesspipe %s %s
  LESSOPEN=| /usr/bin/lesspipe %s
  LIBVIRT_DEFAULT_URI=qemu:///system
  LOGNAME=andrei
  LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
  MAIL=/var/mail/andrei
  OLDPWD=/home/andrei
  PATH=/home/andrei/worker/sandbox/bin:/home/andrei/.local/bin:/home/andrei/Qt/Tools/QtInstallerFramework/3.0/bin:/home/andrei/Qt/5.12.3/gcc_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  PS1=(sandbox) \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ 
  PWD=/home/andrei/worker/qtBuilder/qtBuilder/build
  SHELL=/bin/bash
  SHLVL=1
  SSH_CLIENT=86.57.157.184 54542 22
  SSH_CONNECTION=86.57.157.184 54542 192.168.100.2 22
  SSH_TTY=/dev/pts/0
  TERM=xterm-256color
  USER=andrei
  VIRTUAL_ENV=/home/andrei/worker/sandbox
  XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
  XDG_RUNTIME_DIR=/run/user/1000
  XDG_SESSION_ID=324
  _=/home/andrei/worker/sandbox/bin/buildbot-worker
 using PTY: False
Finished installation
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtbase-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtandroidextras-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtmultimedia-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtandroidextras-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtmultimedia-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtbase-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
-Extracting qtandroidextras-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtgraphicaleffects-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtgraphicaleffects-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
-Extracting qtmultimedia-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtdeclarative-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Extracting qtgraphicaleffects-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtimageformats-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtdeclarative-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtimageformats-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
-Extracting qtimageformats-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtxmlpatterns-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtxmlpatterns-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
-Extracting qtbase-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtserialport-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Extracting qtxmlpatterns-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtquickcontrols-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtserialport-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtquickcontrols-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
-Extracting qtserialport-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qt3d-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Extracting qtdeclarative-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtscxml-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qt3d-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
-Extracting qtquickcontrols-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtspeech-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtscxml-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
Redirected to new URL: http://master.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5140/qt.qt5.5140.android/5.14.0-0-201912110734qtspeech-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z
-Extracting qtspeech-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Extracting qtscxml-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
-Extracting qt3d-Linux-RHEL_7_6-Clang-Android-Android_ANY-Multi.7z...
Traceback (most recent call last):
  File "/home/andrei/.local/bin/aqt", line 9, in <module>
    sys.exit(main())
  File "/home/andrei/.local/lib/python3.6/site-packages/aqt/__init__.py", line 28, in main
    return cli.run()
  File "/home/andrei/.local/lib/python3.6/site-packages/aqt/cli.py", line 218, in run
    args.func(args)
  File "/home/andrei/.local/lib/python3.6/site-packages/aqt/cli.py", line 118, in run_install
    logging=self.logger).install(command=sevenzip, target_dir=output_dir)
  File "/home/andrei/.local/lib/python3.6/site-packages/aqt/installer.py", line 104, in install
    ret_arr = p.map(functools.partial(self.retrieve_archive, command=command, path=base_dir), archives)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/andrei/.local/lib/python3.6/site-packages/aqt/installer.py", line 90, in retrieve_archive
    run([command, 'x', '-aoa', '-bd', '-y', '-o{}'.format(path), archive])
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '7zr': '7zr'
program finished with exit code 1
elapsedTime=27.115227
```
log updated

**Comment by miurahr** [comment]
There are 2 ways.


1. before call command, install dependency
`apt-get instal p7zip`

2.call command with option
`aqt install --outputdir /home/andrei/Qt 5.14.0 linux android --internal`

**Comment by EndrII** [comment]
thanks ))
for what the '--interanl' flag?

**Comment by miurahr** [comment]
'--internal' flag make aptinstall  using  'py7zr',  which is pure python 7-zip library.

**Comment by EndrII** [comment]
@miurahr Thanks for the help.
You have created a great tool.
