### ISSUE TITLE
aqt v3.0.2 Bug error

### ISSUE THREAD

**Issue by bryson834** [miurahr/aqtinstall#777]
**Describe the bug**

**To Reproduce**
1. install `aqt` using this command
2. run `aqt` with this command
3. See error

**Expected behavior**

**`aqt` output**
Add program output to help explain your problem.

```
WARNING : Caught CrcError, terminating installer workers
ERROR   : (3269722604, 943141719, '6.4.3/gcc_64/translations/designer_pl.qm')
Traceback (most recent call last):
  File "/home/bwells/.local/lib/python3.6/site-packages/aqt/installer.py", line 108, in run
    args.func(args)
  File "/home/bwells/.local/lib/python3.6/site-packages/aqt/installer.py", line 348, in run_install_qt
    run_installer(qt_archives.get_packages(), base_dir, sevenzip, keep, _archive_dest)
  File "/home/bwells/.local/lib/python3.6/site-packages/aqt/installer.py", line 1058, in run_installer
    raise e from e
  File "/home/bwells/.local/lib/python3.6/site-packages/aqt/installer.py", line 1034, in run_installer
    pool.starmap(installer, tasks)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
py7zr.exceptions.CrcError: (3269722604, 943141719, '6.4.3/gcc_64/translations/designer_pl.qm')
ERROR   : aqtinstall(aqt) v3.0.2 on Python 3.6.8 [CPython GCC 8.5.0 20210514 (Red Hat 8.5.0-20)]
Working dir: `/home/bwells/dev-scripts`
Arguments: `['/home/bwells/.local/lib/python3.6/site-packages/aqt/__main__.py', 'install-qt', '-b', 'https://mirrors.ocf.berkeley.edu/qt/', '--outputdir', '/home/bwells/workspace/qt', 'linux', 'desktop', '6.4.3', '--modules', 'qtmultimedia', 'qtwebsockets']` Host: `uname_result(system='Linux', node='localhost.localdomain', release='4.18.0-513.24.1.el8_9.x86_64', version='#1 SMP Thu Mar 14 14:20:09 EDT 2024', machine='x86_64', processor='x86_64')`

```

**Desktop (please complete the following information):**
 - OS: RHEL 8.8
 - `aqt` version [v3.0.2]

**Comment by ddalcino** [comment]
* Have you tried using your system’s built-in 7z extractor? See https://aqtinstall.readthedocs.io/en/latest/getting_started.html#external-7-zip-extractor
* What version of py7zr do you have installed?
* Does the problem persist if you use an updated version of aqt (3.1.12 is the current version)
