### ISSUE TITLE
CrcError during install (Qt 6.7.0) on Aliyun Server

### ISSUE THREAD

**Issue by ibicdlcod** [miurahr/aqtinstall#780]
**Describe the bug**

**To Reproduce**
1. install `aqt` using pip
2. run `aqt` with aqt install-qt linux desktop 6.7.0 linux_gcc_64 -m all
3. See error

**Expected behavior**

**`aqt` output**
Add program output to help explain your problem.
WARNING : Caught CrcError, terminating installer workers
ERROR   : (959788162, 3653432065, '6.7.0/gcc_64/plugins/imageformats/libqicns.so')
Traceback (most recent call last):
  File "/home/steam/.local/lib/python3.10/site-packages/aqt/installer.py", line 182, in run
    args.func(args)
  File "/home/steam/.local/lib/python3.10/site-packages/aqt/installer.py", line 447, in run_install_qt
    run_installer(qt_archives.get_packages(), base_dir, sevenzip, keep, _archive_dest)
  File "/home/steam/.local/lib/python3.10/site-packages/aqt/installer.py", line 1189, in run_installer
    raise e from e
  File "/home/steam/.local/lib/python3.10/site-packages/aqt/installer.py", line 1148, in run_installer
    pool.starmap(installer, tasks)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
py7zr.exceptions.CrcError: (959788162, 3653432065, '6.7.0/gcc_64/plugins/imageformats/libqicns.so')
ERROR   : aqtinstall(aqt) v3.1.13 on Python 3.10.12 [CPython GCC 11.4.0]
Working dir: `/home/steam`
Arguments: `['/home/steam/.local/bin/aqt', 'install-qt', 'linux', 'desktop', '6.7.0', 'linux_gcc_64', '-m', 'all']` Host: `uname_result(system='Linux', node='iZj6ceafr1ibcd707jvjiiZ', release='5.15.0-71-generic', version='#78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023', machine='x86_64')`

**Desktop (please complete the following information):**
 - OS: Aliyun Server Ubuntu 22.04 LTS
 - `aqt` version 3.1.13

**Additional context**

**Comment by ddalcino** [comment]
duplicate #777
