### ISSUE TITLE
Caught CrcError, terminating installer workers

### ISSUE THREAD

**Issue by andimik** [miurahr/aqtinstall#786]
**Describe the bug**
installation will terminate with message `Caught CrcError, terminating installer workers`

```
$ aqt install-qt linux desktop 6.6.0 gcc_64 -m qtmultimedia
```

**To Reproduce**
1. install `aqt` using this command
2. run `aqt` with this command
3. See error

```
$ aqt install-qt linux desktop 6.6.0 gcc_64 -m qtmultimedia
INFO    : aqtinstall(aqt) v3.1.15 on Python 3.10.12 [CPython GCC 11.4.0]
INFO    : Downloading qtbase...
INFO    : Downloading qtmultimedia...
INFO    : Downloading qtsvg...
INFO    : Downloading qtdeclarative...
INFO    : Redirected: ftp.fau.de
INFO    : Redirected: ftp.fau.de
INFO    : Redirected: ftp.fau.de
INFO    : Redirected: ftp.fau.de
INFO    : Downloading qttools...
INFO    : Redirected: ftp.fau.de
INFO    : Finished installation of qtmultimedia-Linux-RHEL_8_6-GCC-Linux-RHEL_8_6-X86_64.7z in 71.82849937
INFO    : Downloading qttranslations...
INFO    : Redirected: ftp.fau.de
INFO    : Downloading qtwayland...
INFO    : Redirected: ftp.fau.de
INFO    : Downloading icu...
INFO    : Redirected: ftp.fau.de
WARNING : Caught CrcError, terminating installer workers
ERROR   : (3915944451, 2084624400, '6.6.0/gcc_64/plugins/imageformats/libqsvg.so')
Traceback (most recent call last):
  File "/home/andreas/.local/lib/python3.10/site-packages/aqt/installer.py", line 182, in run
    args.func(args)
  File "/home/andreas/.local/lib/python3.10/site-packages/aqt/installer.py", line 447, in run_install_qt
    run_installer(qt_archives.get_packages(), base_dir, sevenzip, keep, _archive_dest)
  File "/home/andreas/.local/lib/python3.10/site-packages/aqt/installer.py", line 1189, in run_installer
    raise e from e
  File "/home/andreas/.local/lib/python3.10/site-packages/aqt/installer.py", line 1148, in run_installer
    pool.starmap(installer, tasks)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
py7zr.exceptions.CrcError: (3915944451, 2084624400, '6.6.0/gcc_64/plugins/imageformats/libqsvg.so')
ERROR   : aqtinstall(aqt) v3.1.15 on Python 3.10.12 [CPython GCC 11.4.0]
Working dir: `/home/andreas`
Arguments: `['/home/andreas/.local/bin/aqt', 'install-qt', 'linux', 'desktop', '6.6.0', 'gcc_64', '-m', 'qtmultimedia']` Host: `uname_result(system='Linux', node='E535', release='6.2.0-33-generic', version='#33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2', machine='x86_64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues
Please remember to include a copy of this program's output in your report.

```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - `aqt` version 
 
 ```
$ aqt version
INFO    : aqtinstall(aqt) v3.1.15 on Python 3.10.12 [CPython GCC 11.4.0]
```

**Comment by pzhlkj6612** [comment]
Hi! Please try appending `--base https://qt.mirror.constant.com` to your command and run it again.

**Comment by andimik** [comment]
will not continue in this issue, as qt6multimedia is not found.

Closing without contributing here.

**Comment by pzhlkj6612** [comment]
> ... as qt6multimedia is not found.

Well, would you mind explaining a bit more about it?
