### ISSUE TITLE
[Bug]: Qt installation failed

### ISSUE THREAD

**Issue by artiomn** [miurahr/aqtinstall#797]
### Bug description

Qt installation failed.

```
Successfully installed aqtinstall-2.1.0 beautifulsoup4-4.12.3 bs4-0.0.2 certifi-2024.6.2 charset-normalizer-3.3.2 defusedxml-0.7.1 idna-3.7 patch-1.16 requests-2.32.3 semantic-version-2.10.0 soupsieve-2.5 urllib3-2.2.1
C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe -m aqt install-qt windows desktop 6.2.* win64_msvc2019_64 --outputdir D:\a\network-programming-book-code/Qt --modules qtcharts qtwebengine --archives qtbase qtsvg --external 7z
aqtinstall(aqt) v2.1.0 on Python 3.11.9 [CPython MSC v.1938 64 bit (AMD64)]
'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\installer.py", line 108, in run
    args.func(args)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\installer.py", line 261, in run_install_qt
    qt_version: str = str(Cli._determine_qt_version(args.qt_version_spec, os_name, target, arch))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\installer.py", line 223, in _determine_qt_version
    version = choose_highest(version, opt_version_for_spec(ext, spec))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\installer.py", line 208, in opt_version_for_spec
    return MetadataFactory(ArchiveId("qt", host, target, ext), spec=_spec).getList().latest()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\metadata.py", line 435, in getList
    return self._action()
           ^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\metadata.py", line 473, in fetch_versions
    versions = sorted(filter(None, map(get_version, filter(filter_by, versions_extensions))))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\metadata.py", line 600, in iterate_folders
    for row in soup.body.table.find_all("tr"):
               ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
aqtinstall(aqt) v2.1.0 on Python 3.11.9 [CPython MSC v.1938 64 bit (AMD64)]
Working dir: `D:\a\network-programming-book-code\network-programming-book-code`
Arguments: `['C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64\\Lib\\site-packages\\aqt\\__main__.py', 'install-qt', 'windows', 'desktop', '6.2.*', 'win64_msvc2019_64', '--outputdir', 'D:\\a\\network-programming-book-code/Qt', '--modules', 'qtcharts', 'qtwebengine', '--archives', 'qtbase', 'qtsvg', '--external', '7z']` Host: `uname_result(system='Windows', node='fv-az688-228', release='10', version='10.0.20348', machine='AMD64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
```

### Expected behavior

Qt installation passed.

### aqt and python version

3.11.9

### Operating System

Windows

### Relevant log output

```shell
Run jurplel/install-qt-action/action@v3
C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe -m pip install setuptools wheel py7zr==0.19.*
Requirement already satisfied: setuptools in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (65.5.0)
Collecting wheel
  Downloading wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Collecting py7zr==0.19.*
  Downloading py7zr-0.19.2-py3-none-any.whl.metadata (15 kB)
Collecting texttable (from py7zr==0.19.*)
  Downloading texttable-1.7.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting pycryptodomex>=3.6.6 (from py7zr==0.19.*)
  Downloading pycryptodomex-3.20.0-cp35-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting psutil (from py7zr==0.19.*)
  Downloading psutil-5.9.8-cp37-abi3-win_amd64.whl.metadata (22 kB)
Collecting pyzstd>=0.14.4 (from py7zr==0.19.*)
  Downloading pyzstd-0.16.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting pyppmd<0.19.0,>=0.18.1 (from py7zr==0.19.*)
  Downloading pyppmd-0.18.3-cp311-cp311-win_amd64.whl.metadata (5.4 kB)
Collecting pybcj>=0.6.0 (from py7zr==0.19.*)
  Downloading pybcj-1.0.2-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting multivolumefile>=0.2.3 (from py7zr==0.19.*)
  Downloading multivolumefile-0.2.3-py3-none-any.whl.metadata (6.3 kB)
Collecting brotli>=1.0.9 (from py7zr==0.19.*)
  Downloading Brotli-1.1.0-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
Collecting inflate64>=0.1.2 (from py7zr==0.19.*)
  Downloading inflate64-1.0.0-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Downloading py7zr-0.19.2-py3-none-any.whl (65 kB)
   ---------------------------------------- 65.8/65.8 kB 3.5 MB/s eta 0:00:00
Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
   ---------------------------------------- 65.8/65.8 kB 3.5 MB/s eta 0:00:00
Downloading Brotli-1.1.0-cp311-cp311-win_amd64.whl (357 kB)
   ---------------------------------------- 357.3/357.3 kB 5.5 MB/s eta 0:00:00
Downloading inflate64-1.0.0-cp311-cp311-win_amd64.whl (35 kB)
Downloading multivolumefile-0.2.3-py3-none-any.whl (17 kB)
Downloading pybcj-1.0.2-cp311-cp311-win_amd64.whl (24 kB)
Downloading pycryptodomex-3.20.0-cp35-abi3-win_amd64.whl (1.8 MB)
   ---------------------------------------- 1.8/1.8 MB 16.1 MB/s eta 0:00:00
Downloading pyppmd-0.18.3-cp311-cp311-win_amd64.whl (46 kB)
   ---------------------------------------- 46.1/46.1 kB 2.2 MB/s eta 0:00:00
Downloading pyzstd-0.16.0-cp311-cp311-win_amd64.whl (245 kB)
   --------------------------------------- 245.7/245.7 kB 14.7 MB/s eta 0:00:00
Downloading psutil-5.9.8-cp37-abi3-win_amd64.whl (255 kB)
   ---------------------------------------- 255.1/255.1 kB 7.9 MB/s eta 0:00:00
Downloading texttable-1.7.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: texttable, brotli, wheel, pyzstd, pyppmd, pycryptodomex, pybcj, psutil, multivolumefile, inflate64, py7zr
Successfully installed brotli-1.1.0 inflate64-1.0.0 multivolumefile-0.2.3 psutil-5.9.8 py7zr-0.19.2 pybcj-1.0.2 pycryptodomex-3.20.0 pyppmd-0.18.3 pyzstd-0.16.0 texttable-1.7.0 wheel-0.43.0
C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe -m pip install aqtinstall==2.1.*
Collecting aqtinstall==2.1.*
  Downloading aqtinstall-2.1.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting requests (from aqtinstall==2.1.*)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting semantic-version (from aqtinstall==2.1.*)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting patch>=1.16 (from aqtinstall==2.1.*)
  Downloading patch-1.16.zip (12 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: py7zr>=0.18.3 in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (from aqtinstall==2.1.*) (0.19.2)
Requirement already satisfied: texttable in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (from aqtinstall==2.1.*) (1.7.0)
Collecting bs4 (from aqtinstall==2.1.*)
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Collecting defusedxml (from aqtinstall==2.1.*)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: pycryptodomex>=3.6.6 in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (from py7zr>=0.18.3->aqtinstall==2.1.*) (3.20.0)
Requirement already satisfied: psutil in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (from py7zr>=0.18.3->aqtinstall==2.1.*) (5.9.8)
Requirement already satisfied: pyzstd>=0.14.4 in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (from py7zr>=0.18.3->aqtinstall==2.1.*) (0.16.0)
Requirement already satisfied: pyppmd<0.19.0,>=0.18.1 in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (from py7zr>=0.18.3->aqtinstall==2.1.*) (0.18.3)
Requirement already satisfied: pybcj>=0.6.0 in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (from py7zr>=0.18.3->aqtinstall==2.1.*) (1.0.2)
Requirement already satisfied: multivolumefile>=0.2.3 in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (from py7zr>=0.18.3->aqtinstall==2.1.*) (0.2.3)
Requirement already satisfied: brotli>=1.0.9 in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (from py7zr>=0.18.3->aqtinstall==2.1.*) (1.1.0)
Requirement already satisfied: inflate64>=0.1.2 in c:\hostedtoolcache\windows\python\3.11.9\x64\lib\site-packages (from py7zr>=0.18.3->aqtinstall==2.1.*) (1.0.0)
Collecting beautifulsoup4 (from bs4->aqtinstall==2.1.*)
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting charset-normalizer<4,>=2 (from requests->aqtinstall==2.1.*)
  Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->aqtinstall==2.1.*)
  Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->aqtinstall==2.1.*)
  Downloading urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests->aqtinstall==2.1.*)
  Downloading certifi-2024.6.2-py3-none-any.whl.metadata (2.2 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->bs4->aqtinstall==2.1.*)
  Downloading soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Downloading aqtinstall-2.1.0-py2.py3-none-any.whl (53 kB)
   ---------------------------------------- 54.0/54.0 kB 2.7 MB/s eta 0:00:00
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ---------------------------------------- 64.9/64.9 kB 1.7 MB/s eta 0:00:00
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading certifi-2024.6.2-py3-none-any.whl (164 kB)
   ---------------------------------------- 164.4/164.4 kB 5.0 MB/s eta 0:00:00
Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
   ---------------------------------------- 99.9/99.9 kB 6.0 MB/s eta 0:00:00
Downloading idna-3.7-py3-none-any.whl (66 kB)
   ---------------------------------------- 66.8/66.8 kB 3.5 MB/s eta 0:00:00
Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
   ---------------------------------------- 121.1/121.1 kB 7.4 MB/s eta 0:00:00
Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
   ---------------------------------------- 147.9/147.9 kB 8.6 MB/s eta 0:00:00
Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Building wheels for collected packages: patch
  Building wheel for patch (setup.py): started
  Building wheel for patch (setup.py): finished with status 'done'
  Created wheel for patch: filename=patch-1.16-py3-none-any.whl size=12394 sha256=23671a4dfa927e171c59f0d359f5ac0fd83f9c00ce4bc9880f250aef8154f873
  Stored in directory: c:\users\runneradmin\appdata\local\pip\cache\wheels\cb\ee\c0\8b7da5d06750d049187f4672e1fd70fade43ec0d2ee5b5fcda
Successfully built patch
Installing collected packages: patch, urllib3, soupsieve, semantic-version, idna, defusedxml, charset-normalizer, certifi, requests, beautifulsoup4, bs4, aqtinstall
Successfully installed aqtinstall-2.1.0 beautifulsoup4-4.12.3 bs4-0.0.2 certifi-2024.6.2 charset-normalizer-3.3.2 defusedxml-0.7.1 idna-3.7 patch-1.16 requests-2.32.3 semantic-version-2.10.0 soupsieve-2.5 urllib3-2.2.1
C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe -m aqt install-qt windows desktop 6.2.* win64_msvc2019_64 --outputdir D:\a\network-programming-book-code/Qt --modules qtcharts qtwebengine --archives qtbase qtsvg --external 7z
aqtinstall(aqt) v2.1.0 on Python 3.11.9 [CPython MSC v.1938 64 bit (AMD64)]
'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\installer.py", line 108, in run
    args.func(args)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\installer.py", line 261, in run_install_qt
    qt_version: str = str(Cli._determine_qt_version(args.qt_version_spec, os_name, target, arch))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\installer.py", line 223, in _determine_qt_version
    version = choose_highest(version, opt_version_for_spec(ext, spec))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\installer.py", line 208, in opt_version_for_spec
    return MetadataFactory(ArchiveId("qt", host, target, ext), spec=_spec).getList().latest()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\metadata.py", line 435, in getList
    return self._action()
           ^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\metadata.py", line 473, in fetch_versions
    versions = sorted(filter(None, map(get_version, filter(filter_by, versions_extensions))))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\aqt\metadata.py", line 600, in iterate_folders
    for row in soup.body.table.find_all("tr"):
               ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
aqtinstall(aqt) v2.1.0 on Python 3.11.9 [CPython MSC v.1938 64 bit (AMD64)]
Working dir: `D:\a\network-programming-book-code\network-programming-book-code`
Arguments: `['C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64\\Lib\\site-packages\\aqt\\__main__.py', 'install-qt', 'windows', 'desktop', '6.2.*', 'win64_msvc2019_64', '--outputdir', 'D:\\a\\network-programming-book-code/Qt', '--modules', 'qtcharts', 'qtwebengine', '--archives', 'qtbase', 'qtsvg', '--external', '7z']` Host: `uname_result(system='Windows', node='fv-az688-228', release='10', version='10.0.20348', machine='AMD64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
Please remember to include a copy of this program's output in your report.
Error: Error: The process 'C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe' failed with exit code 254
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pzhlkj6612** [comment]
Hi!

> aqtinstall(aqt) v2.1.0

Well, it's too old. The latest version if aqt is v3. What is your install-qt-action config in your workflow file?

**Comment by artiomn** [comment]
> Hi!
> 
> > aqtinstall(aqt) v2.1.0
> 
> Well, it's too old. The latest version if aqt is v3. What is your install-qt-action config in your workflow file?

```
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.*'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          # dir: '${{ github.workspace }}/example/'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          archives: 'qtbase qtsvg'
          cache: 'false'
          cache-key-prefix: 'install-qt-action'
          setup-python: 'true'
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==2.1.*'
          py7zrversion: '==0.19.*'
          extra: '--external 7z'
```

Should I just upgrade aqtversion to 3.0.*?

**Comment by pzhlkj6612** [comment]
Please try this:

```YAML
      - name: Install Qt
        uses: jurplel/install-qt-action@v4  # v4 is available
        with:
          version: '6.2.*'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

```

It looks like you were directly using the example config in the README [^1]. It's too complicated. Let's start from a simpler one.

[^1]: https://github.com/jurplel/install-qt-action/blob/0fe81f805e5f2d6d4e45809cb9d20822e6c81b2d/README.md#example-with-all-arguments

**Comment by artiomn** [comment]
Yes, it works. The builds are passing again. Thank you.
