### ISSUE TITLE
[Bug]:  CI failed: combination detection 

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#807]
### Bug description

CI `combination.json` failed 

### Expected behavior

Run CI without error

### aqt and python version

Python 3.12

### Operating System

Linux/Unix

### Relevant log output

```shell
INFO    : Fetching arches
Traceback (most recent call last):
  File "/home/runner/work/aqtinstall/aqtinstall/ci/generate_combinations.py", line 215, in <module>
    main(filename=json_filename, is_write_file=args.write, is_verbose=args.verbose)
  File "/home/runner/work/aqtinstall/aqtinstall/ci/generate_combinations.py", line 147, in main
    actual = [generate_combos(new_archive=expect[0]["new_archive"])]
  File "/home/runner/work/aqtinstall/aqtinstall/ci/generate_combinations.py", line 120, in generate_combos
    "qt": merge_records(iter_arches()),
  File "/home/runner/work/aqtinstall/aqtinstall/ci/generate_combinations.py", line 108, in merge_records
    for record in arch_records:
  File "/home/runner/work/aqtinstall/aqtinstall/ci/generate_combinations.py", line 48, in iter_arches
    for arch_name in MetadataFactory(archive_id, architectures_ver=version).getList():
  File "/home/runner/work/aqtinstall/aqtinstall/aqt/metadata.py", line 620, in getList
    return self._action()
  File "/home/runner/work/aqtinstall/aqtinstall/aqt/metadata.py", line 600, in <lambda>
    self._action = lambda: self.fetch_arches(self._to_version(ver_str, None))
  File "/home/runner/work/aqtinstall/aqtinstall/aqt/metadata.py", line 720, in _to_version
    raise CliInputError(msg)
aqt.exceptions.CliInputError: There is no latest version of Qt with the criteria 'qt/all_os/qt'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pzhlkj6612** [comment]
Is this the chance to drop the offline validation? #748.

**Comment by miurahr** [comment]
Lets do it!

**Comment by pzhlkj6612** [comment]
Is there something I can help?

**Comment by miurahr** [comment]
I think we can remove lines https://github.com/miurahr/aqtinstall/blob/master/aqt/installer.py#L420-L423 and related methods.  Could you try the modification? If it works, it is a chance to raise Pull-Request.

**Comment by miurahr** [comment]
#812

**Comment by pzhlkj6612** [comment]
> could you mind to review the change?

I'll look into that PR in 3 days.

**Comment by pzhlkj6612** [comment]
@miurahr , this issue should be closed.
