### ISSUE TITLE
[Bug]: multiple problems with list-qt and android

### ISSUE THREAD

**Issue by tsteven4** [miurahr/aqtinstall#860]
### Bug description

The following commands fail:
aqt list-qt linux android
aqt list-qt linux android --arch 6.8.1
aqt list-qt linux android --modules 6.8.1 android_armv7
The last two work with 6.5.3.

### Expected behavior

no ERRORs, correct list output.

I ran this script
[tryandroidlist.txt](https://github.com/user-attachments/files/18186229/tryandroidlist.txt)
and captured standard output and standard error:
[list.log](https://github.com/user-attachments/files/18186220/list.log)

aqt was from fa497729d

### aqt and python version

INFO    : aqtinstall(aqt) v3.1.21.dev18 on Python 3.12.3 [CPython GCC 13.2.0]

### Operating System

Linux/Unix

### Relevant log output

```shell
+ aqt list-qt linux android
ERROR   : Invalid version string '7'
Traceback (most recent call last):
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/installer.py", line 180, in run
    args.func(args)
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/installer.py", line 601, in run_list_qt
    show_list(meta)
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/metadata.py", line 1090, in show_list
    output = meta.getList()
             ^^^^^^^^^^^^^^
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/metadata.py", line 664, in getList
    return self._action()
           ^^^^^^^^^^^^^^
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/metadata.py", line 701, in fetch_versions
    versions = sorted([ver for ver, ext in versions_extensions if ver is not None and filter_by(ver, ext)])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/metadata.py", line 832, in folder_to_version_extension
    get_semantic_version(qt_ver=ver, is_preview="preview" in ext),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/metadata.py", line 204, in get_semantic_version
    raise ValueError("Invalid version string '{}'".format(qt_ver))
ValueError: Invalid version string '7'
ERROR   : aqtinstall(aqt) v3.1.21.dev18 on Python 3.12.3 [CPython GCC 13.2.0]
Working dir: `/home/tsteven4/work/tsaqt`
Arguments: `['/home/tsteven4/aqttest-venv/bin/aqt', 'list-qt', 'linux', 'android']` Host: `uname_result(system='Linux', node='PEDALDAMNIT', release='5.15.167.4-microsoft-standard-WSL2', version='#1 SMP Tue Nov 5 00:21:55 UTC 2024', machine='x86_64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues
Please remember to include a copy of this program's output in your report.
+ set +x
2024-12-18 09:38:25,317 - aqt.main - ERROR - installer 140396262293632 Invalid version string '7'
Traceback (most recent call last):
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/installer.py", line 180, in run
    args.func(args)
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/installer.py", line 601, in run_list_qt
    show_list(meta)
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/metadata.py", line 1090, in show_list
    output = meta.getList()
             ^^^^^^^^^^^^^^
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/metadata.py", line 664, in getList
    return self._action()
           ^^^^^^^^^^^^^^
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/metadata.py", line 701, in fetch_versions
    versions = sorted([ver for ver, ext in versions_extensions if ver is not None and filter_by(ver, ext)])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/metadata.py", line 832, in folder_to_version_extension
    get_semantic_version(qt_ver=ver, is_preview="preview" in ext),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tsteven4/aqttest-venv/lib/python3.12/site-packages/aqt/metadata.py", line 204, in get_semantic_version
    raise ValueError("Invalid version string '{}'".format(qt_ver))
ValueError: Invalid version string '7'
2024-12-18 09:38:25,317 - aqt.main - ERROR - installer 140396262293632 aqtinstall(aqt) v3.1.21.dev18 on Python 3.12.3 [CPython GCC 13.2.0]
Working dir: `/home/tsteven4/work/tsaqt`
Arguments: `['/home/tsteven4/aqttest-venv/bin/aqt', 'list-qt', 'linux', 'android']` Host: `uname_result(system='Linux', node='PEDALDAMNIT', release='5.15.167.4-microsoft-standard-WSL2', version='#1 SMP Tue Nov 5 00:21:55 UTC 2024', machine='x86_64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues
Please remember to include a copy of this program's output in your report.
-------------------------------------------------------------
+ aqt list-qt linux android --arch 6.5.3
android_arm64_v8a android_armv7 android_x86 android_x86_64
+ set +x
2024-12-18 09:38:25,468 - aqt.helper - DEBUG - helper 140621306953856 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_653_arm64_v8a/Updates.xml.sha256
2024-12-18 09:38:26,782 - aqt.helper - DEBUG - helper 140621306953856 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_653_armv7/Updates.xml.sha256
2024-12-18 09:38:28,118 - aqt.helper - DEBUG - helper 140621306953856 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_653_x86/Updates.xml.sha256
2024-12-18 09:38:29,456 - aqt.helper - DEBUG - helper 140621306953856 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_653_x86_64/Updates.xml.sha256
-------------------------------------------------------------
+ aqt list-qt linux android --arch 6.8.1
ERROR   : No architectures available for this request.
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt linux android' to show versions of Qt available.
+ set +x
2024-12-18 09:38:30,875 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_armv7/Updates.xml.sha256
2024-12-18 09:38:31,501 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_armv7/Updates.xml.sha256
2024-12-18 09:38:32,144 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_armv7/Updates.xml.sha256
2024-12-18 09:38:32,767 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_armv7/Updates.xml.sha256
2024-12-18 09:38:33,390 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_armv7/Updates.xml.sha256
2024-12-18 09:38:34,073 - aqt.metadata - DEBUG - metadata 140235240202368 Failed to download checksum for the file 'Updates.xml' from mirrors '['https://download.qt.io']
2024-12-18 09:38:34,073 - aqt.metadata - DEBUG - metadata 140235240202368 Failed to retrieve arches list with extension `armv7`. Please check that this extension exists for this version of Qt: if not, code changes will be necessary.
2024-12-18 09:38:34,074 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_x86/Updates.xml.sha256
2024-12-18 09:38:34,702 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_x86/Updates.xml.sha256
2024-12-18 09:38:35,330 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_x86/Updates.xml.sha256
2024-12-18 09:38:35,953 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_x86/Updates.xml.sha256
2024-12-18 09:38:36,599 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_x86/Updates.xml.sha256
2024-12-18 09:38:37,261 - aqt.metadata - DEBUG - metadata 140235240202368 Failed to download checksum for the file 'Updates.xml' from mirrors '['https://download.qt.io']
2024-12-18 09:38:37,261 - aqt.metadata - DEBUG - metadata 140235240202368 Failed to retrieve arches list with extension `x86`. Please check that this extension exists for this version of Qt: if not, code changes will be necessary.
2024-12-18 09:38:37,261 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_x86_64/Updates.xml.sha256
2024-12-18 09:38:37,898 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_x86_64/Updates.xml.sha256
2024-12-18 09:38:38,520 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_x86_64/Updates.xml.sha256
2024-12-18 09:38:39,153 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_x86_64/Updates.xml.sha256
2024-12-18 09:38:39,787 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_x86_64/Updates.xml.sha256
2024-12-18 09:38:40,410 - aqt.metadata - DEBUG - metadata 140235240202368 Failed to download checksum for the file 'Updates.xml' from mirrors '['https://download.qt.io']
2024-12-18 09:38:40,410 - aqt.metadata - DEBUG - metadata 140235240202368 Failed to retrieve arches list with extension `x86_64`. Please check that this extension exists for this version of Qt: if not, code changes will be necessary.
2024-12-18 09:38:40,410 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_arm64_v8a/Updates.xml.sha256
2024-12-18 09:38:41,043 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_arm64_v8a/Updates.xml.sha256
2024-12-18 09:38:41,700 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_arm64_v8a/Updates.xml.sha256
2024-12-18 09:38:42,325 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_arm64_v8a/Updates.xml.sha256
2024-12-18 09:38:42,964 - aqt.helper - DEBUG - helper 140235240202368 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_arm64_v8a/Updates.xml.sha256
2024-12-18 09:38:43,599 - aqt.metadata - DEBUG - metadata 140235240202368 Failed to download checksum for the file 'Updates.xml' from mirrors '['https://download.qt.io']
2024-12-18 09:38:43,599 - aqt.metadata - DEBUG - metadata 140235240202368 Failed to retrieve arches list with extension `arm64_v8a`. Please check that this extension exists for this version of Qt: if not, code changes will be necessary.
2024-12-18 09:38:43,601 - aqt.main - ERROR - installer 140235240202368 No architectures available for this request.
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt linux android' to show versions of Qt available.
-------------------------------------------------------------
+ aqt list-qt linux android --modules 6.5.3 android_armv7
qt3d qt5compat qtcharts qtconnectivity qtdatavis3d qtgrpc qthttpserver qtimageformats qtlocation qtlottie qtmultimedia qtnetworkauth qtpositioning qtquick3d qtquick3dphysics qtquicktimeline qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtshadertools qtspeech qtvirtualkeyboard qtwebchannel qtwebsockets qtwebview
+ set +x
2024-12-18 09:38:43,768 - aqt.helper - DEBUG - helper 139985458491520 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_653_armv7/Updates.xml.sha256
-------------------------------------------------------------
+ aqt list-qt linux android --modules 6.8.1 android_armv7
ERROR   : Failed to download checksum for the file 'Updates.xml' from mirrors '['https://download.qt.io']
==============================Suggested follow-up:==============================
* Check your internet connection
* Consider modifying `requests.max_retries_to_retrieve_hash` in settings.ini
* Consider modifying `mirrors.trusted_mirrors` in settings.ini (see https://aqtinstall.readthedocs.io/en/stable/configuration.html#configuration)
* Please use 'aqt list-qt linux android' to show versions of Qt available.
* Please use 'aqt list-qt linux android --arch <QT_VERSION>' to list valid architectures.
usage: aqt [-h] [-c CONFIG]
           {install-qt,install-tool,install-doc,install-example,install-src,list-qt,list-tool,list-doc,list-example,list-src,help,version}
           ...

Another unofficial Qt Installer.
aqt helps you install Qt SDK, tools, examples and others

options:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Configuration ini file.

subcommands:
  aqt accepts several subcommands:
  install-* subcommands are commands that install components
  list-* subcommands are commands that show available components

  {install-qt,install-tool,install-doc,install-example,install-src,list-qt,list-tool,list-doc,list-example,list-src,help,version}
                        Please refer to each help message by using '--help' with each subcommand
+ set +x
2024-12-18 09:38:59,741 - aqt.helper - DEBUG - helper 140074226909312 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_armv7/Updates.xml.sha256
2024-12-18 09:39:00,372 - aqt.helper - DEBUG - helper 140074226909312 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_armv7/Updates.xml.sha256
2024-12-18 09:39:01,019 - aqt.helper - DEBUG - helper 140074226909312 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_armv7/Updates.xml.sha256
2024-12-18 09:39:14,863 - aqt.helper - DEBUG - helper 140074226909312 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_armv7/Updates.xml.sha256
2024-12-18 09:39:33,180 - aqt.helper - DEBUG - helper 140074226909312 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_681/qt6_681_armv7/Updates.xml.sha256
2024-12-18 09:39:33,795 - aqt.main - ERROR - installer 140074226909312 Failed to download checksum for the file 'Updates.xml' from mirrors '['https://download.qt.io']
==============================Suggested follow-up:==============================
* Check your internet connection
* Consider modifying `requests.max_retries_to_retrieve_hash` in settings.ini
* Consider modifying `mirrors.trusted_mirrors` in settings.ini (see https://aqtinstall.readthedocs.io/en/stable/configuration.html#configuration)
* Please use 'aqt list-qt linux android' to show versions of Qt available.
* Please use 'aqt list-qt linux android --arch <QT_VERSION>' to list valid architectures.
-------------------------------------------------------------
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zyfy29** [comment]
It's likely to be fixed since v3.3.0

**Comment by Kidev** [comment]
Indeed it works as of v3.3.0. However, those:
```console
kidev:~$ aqt list-qt linux android --arch 6.8.1
kidev:~$ aqt list-qt linux android --modules 6.8.1 android_armv7
```
Should be using `all_os` as `os` for Qt 6.7+
```console
kidev:~$ aqt list-qt all_os android --arch 6.8.1
kidev:~$ aqt list-qt all_os android --modules 6.8.1 android_armv7
```

**Comment by Kidev** [comment]
@stefan894 You have a very outdated aqtinstall version (`v3.1.11`), this does not happen with the latest versions
