### ISSUE TITLE
Error extracting a lib on Ubuntu

### ISSUE THREAD

**Issue by Luni-4** [miurahr/aqtinstall#92]
When the `pip3 install aqtinstall==0.7.1` command is run, sometimes we get the following error:

```
2020-02-18 23:37:53,175 - aqt - INFO - -Extracting qtremoteobjects-Linux-RHEL_7_4-GCC-Linux-RHEL_7_4-X86_64.7z...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/aqt/__main__.py", line 28, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/aqt/__init__.py", line 38, in main
    return cli.run()
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/aqt/cli.py", line 218, in run
args.func(args)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/aqt/cli.py", line 122, in run_install
    logging=self.logger).install(command=sevenzip, target_dir=output_dir)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/aqt/installer.py", line 94, in install
    ret_arr = p.map(functools.partial(self.retrieve_archive, command=command, path=base_dir), archives)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/aqt/installer.py", line 83, in retrieve_archive
    os.unlink(archive)
FileNotFoundError: [Errno 2] No such file or directory: 'qtscxml-Linux-RHEL_7_4-GCC-Linux-RHEL_7_4-X86_64.7z'
```

It didn't happen before, so is it related to `aqtinstall`? Thanks in advance for your help! :)

**Comment by miurahr** [comment]
Could you try with aqtinstall == 0.7.3?

**Comment by miurahr** [comment]
[v0.7.4](https://pypi.org/project/aqtinstall/0.7.4/) is released. Any help?

**Comment by Luni-4** [comment]
Thanks @miurahr! It seems to work now! :)
