### ISSUE TITLE
Error when installing Qt 5.12.7 desktop mac

### ISSUE THREAD

**Issue by MartinDelille** [miurahr/aqtinstall#94]
I wanted to try `aqtinstall` but I have the following error:

```
aqt install 5.12.7 mac desktop
Finished installation
-Downloading https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtgraphicaleffects-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtmultimedia-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
Redirected to new URL: http://mirrors.ukfast.co.uk/sites/qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
Redirected to new URL: http://mirrors.ukfast.co.uk/sites/qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtgraphicaleffects-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
Redirected to new URL: http://mirrors.ukfast.co.uk/sites/qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtmultimedia-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
-Extracting qtgraphicaleffects-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qttranslations-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
Redirected to new URL: http://mirrors.ukfast.co.uk/sites/qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qttranslations-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
-Extracting qtmultimedia-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtxmlpatterns-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
Redirected to new URL: http://mirrors.ukfast.co.uk/sites/qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtxmlpatterns-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
-Extracting qttranslations-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qttools-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
Redirected to new URL: http://mirrors.ukfast.co.uk/sites/qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qttools-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
-Extracting qtxmlpatterns-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qt3d-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
Redirected to new URL: http://mirrors.ukfast.co.uk/sites/qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qt3d-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
-Extracting qt3d-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtserialbus-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
Redirected to new URL: http://mirrors.ukfast.co.uk/sites/qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtserialbus-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
-Extracting qtserialbus-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
-Downloading https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtspeech-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
Redirected to new URL: http://mirrors.ukfast.co.uk/sites/qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtspeech-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z
-Extracting qtspeech-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
-Extracting qttools-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
-Extracting qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...
Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 9, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/aqt/__init__.py", line 28, in main
    return cli.run()
  File "/usr/local/lib/python3.7/site-packages/aqt/cli.py", line 218, in run
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/aqt/cli.py", line 118, in run_install
    logging=self.logger).install(command=sevenzip, target_dir=output_dir)
  File "/usr/local/lib/python3.7/site-packages/aqt/installer.py", line 104, in install
    ret_arr = p.map(functools.partial(self.retrieve_archive, command=command, path=base_dir), archives)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/site-packages/aqt/installer.py", line 90, in retrieve_archive
    run([command, 'x', '-aoa', '-bd', '-y', '-o{}'.format(path), archive])
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '7zr': '7zr'
```

What is `7zr`?

**Comment by MartinDelille** [comment]
Ok after looking at the [azure pipeline mac job](https://github.com/miurahr/aqtinstall/blob/master/azure-pipelines.yml#L15-L24) I noticed I was missing something: `brew install p7zip`

Like #93, a missing `p7zip` installation should display a more expressive error.

**Comment by miurahr** [comment]
What version of aqtinstall you use?
Most recent v0.7.4 does not use `p7zip` in default.

**Comment by MartinDelille** [comment]
How can I guess my current `aqt` version?  `aqt version` and `aqt --version` returns both an error.

**Comment by miurahr** [comment]
Oh, here is no version option yet.
You can use 'pip show' command

```
$ pip show aqtinstall
Name: aqtinstall
Version: 0.7.4
Summary: Another unofficial Qt installer
Home-page: http://github.com/miurahr/aqtinstall
Author: Hiroshi Miura
Author-email: miurahr@linux.com
License: MIT
Location: /home/miurahr/.virtualenvs/aqtinstall/lib/python3.6/site-packages
Requires: wheel, requests, packaging, py7zr
Required-by: 
```

**Comment by MartinDelille** [comment]
Thanks!

```
$ pip show aqtinstall
Name: aqtinstall
Version: 0.6
Summary: Another unofficial Qt installer
Home-page: http://github.com/miurahr/aqtinstall
Author: Hioshi Miura
Author-email: miurahr@linux.com
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires: py7zr, six, requests, packaging
Required-by:
```

**Comment by miurahr** [comment]
v0.6 depends on p7zip command whichi is installed in default folder.
v0.7.4 uses py7zr library to extract and it also support '-E <7z command full path>' option.

**Comment by MartinDelille** [comment]
Ok so if I understand well, it'll be fixed once the new version will be available on `pip`.

Thanks for your time!
